2020-10-14 16:25:16,479 -  nornir.core -     INFO -        run() - Running task 'port_cfg_xml_generation' with args {'svc_dict': {'svc': {'service': {'type': 'L2V', 'class': 'TST', 'descr': 'Ansible', 'svc_id': 500013}, 'attach_circuit_wan': [{'hostname': 'PE01LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'dot1q', 'mtu': '9212', 'vlan': '12', 'sap_descr': 'Automation', 'qos': 'BE', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE01LT2', 'port': '1/2/11', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'qinq', 'mtu': '9212', 'vlan': '100.*', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE02LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'null', 'mtu': '9212', 'vlan': '', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}]}}, 'attr_dict': {'pe': {'loopback': {'PE01LT2': {'id': 1}, 'PE02LT2': {'id': 2}}, 'qos': {'BE': {'fprdgrp': 'dc-vxlan-be', 'qos_id': 1, 'queue_id': 1}, 'AF': {'fprdgrp': 'dc-vxlan-af', 'qos_id': 6003, 'queue_id': 3}, 'EF': {'fprdgrp': 'dc-vxlan-ef', 'qos_id': 6001, 'queue_id': 6}, 'H1': {'fprdgrp': 'dc-vxlan-h1', 'qos_id': 6000, 'queue_id': 7}}}}} on 2 hosts
2020-10-14 16:25:16,489 -  nornir.core -     INFO -        run() - Running task 'svc_cfg_xml_generation' with args {'svc_dict': {'svc': {'service': {'type': 'L2V', 'class': 'TST', 'descr': 'Ansible', 'svc_id': 500013}, 'attach_circuit_wan': [{'hostname': 'PE01LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'dot1q', 'mtu': '9212', 'vlan': '12', 'sap_descr': 'Automation', 'qos': 'BE', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE01LT2', 'port': '1/2/11', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'qinq', 'mtu': '9212', 'vlan': '100.*', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE02LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'null', 'mtu': '9212', 'vlan': '', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}]}}, 'attr_dict': {'pe': {'loopback': {'PE01LT2': {'id': 1}, 'PE02LT2': {'id': 2}}, 'qos': {'BE': {'fprdgrp': 'dc-vxlan-be', 'qos_id': 1, 'queue_id': 1}, 'AF': {'fprdgrp': 'dc-vxlan-af', 'qos_id': 6003, 'queue_id': 3}, 'EF': {'fprdgrp': 'dc-vxlan-ef', 'qos_id': 6001, 'queue_id': 6}, 'H1': {'fprdgrp': 'dc-vxlan-h1', 'qos_id': 6000, 'queue_id': 7}}}}} on 2 hosts
2020-10-14 16:25:16,501 -  nornir.core -     INFO -        run() - Running task 'sap_cfg_xml_generation' with args {'svc_dict': {'svc': {'service': {'type': 'L2V', 'class': 'TST', 'descr': 'Ansible', 'svc_id': 500013}, 'attach_circuit_wan': [{'hostname': 'PE01LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'dot1q', 'mtu': '9212', 'vlan': '12', 'sap_descr': 'Automation', 'qos': 'BE', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE01LT2', 'port': '1/2/11', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'qinq', 'mtu': '9212', 'vlan': '100.*', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE02LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'null', 'mtu': '9212', 'vlan': '', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}]}}, 'attr_dict': {'pe': {'loopback': {'PE01LT2': {'id': 1}, 'PE02LT2': {'id': 2}}, 'qos': {'BE': {'fprdgrp': 'dc-vxlan-be', 'qos_id': 1, 'queue_id': 1}, 'AF': {'fprdgrp': 'dc-vxlan-af', 'qos_id': 6003, 'queue_id': 3}, 'EF': {'fprdgrp': 'dc-vxlan-ef', 'qos_id': 6001, 'queue_id': 6}, 'H1': {'fprdgrp': 'dc-vxlan-h1', 'qos_id': 6000, 'queue_id': 7}}}}} on 2 hosts
2020-10-14 16:25:16,516 -  nornir.core -     INFO -        run() - Running task 'full_cfg_xml_generation' with args {'svc_dict': {'svc': {'service': {'type': 'L2V', 'class': 'TST', 'descr': 'Ansible', 'svc_id': 500013}, 'attach_circuit_wan': [{'hostname': 'PE01LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'dot1q', 'mtu': '9212', 'vlan': '12', 'sap_descr': 'Automation', 'qos': 'BE', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE01LT2', 'port': '1/2/11', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'qinq', 'mtu': '9212', 'vlan': '100.*', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE02LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'null', 'mtu': '9212', 'vlan': '', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}]}}} on 2 hosts
2020-10-14 16:25:16,528 -  nornir.core -     INFO -        run() - Running task 'send_xml_payload' with args {} on 2 hosts
2020-10-14 16:25:17,246 - nornir.core.task -    ERROR -      start() - Host 'PE01LT2': task 'XML payload through Netconf' failed with traceback:
Traceback (most recent call last):
  File "/home/fouine/.local/lib/python3.8/site-packages/scrapli/transport/ptyprocess.py", line 376, in read
    s = self.fileobj.read1(size)
OSError: [Errno 5] Input/output error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 85, in _authenticate
    new_output = self.session.read()
  File "/home/fouine/.local/lib/python3.8/site-packages/scrapli/transport/ptyprocess.py", line 381, in read
    raise EOFError("End Of File (EOF). Exception style platform.")
EOFError: End Of File (EOF). Exception style platform.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir_scrapli/tasks/netconf_edit_config.py", line 27, in netconf_edit_config
    scrapli_conn = task.host.get_connection("scrapli_netconf", task.nornir.config)
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/inventory.py", line 440, in get_connection
    self.open_connection(
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/inventory.py", line 492, in open_connection
    conn_obj.open(
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir_scrapli/connection.py", line 157, in open
    connection.open()
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/driver/driver.py", line 55, in open
    login_bytes = self.transport.open_netconf()
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 35, in open_netconf
    login_bytes = self._open_netconf_pty()
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 59, in _open_netconf_pty
    login_bytes: bytes = self._authenticate()
  File "/home/fouine/.local/lib/python3.8/site-packages/scrapli/decorators.py", line 113, in decorate
    return self.multiprocessing_timeout(
  File "/home/fouine/.local/lib/python3.8/site-packages/scrapli/decorators.py", line 301, in multiprocessing_timeout
    result = future.get(timeout=self.timeout_duration)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 97, in _authenticate
    raise ScrapliAuthenticationFailed(msg) from exc
scrapli.exceptions.ScrapliAuthenticationFailed: Failed to open connection to host PE01LT2. Do you need to disable `auth_strict_key`?

2020-10-14 16:25:17,246 - nornir.core.task -    ERROR -      start() - Host 'PE02LT2': task 'XML payload through Netconf' failed with traceback:
Traceback (most recent call last):
  File "/home/fouine/.local/lib/python3.8/site-packages/scrapli/transport/ptyprocess.py", line 376, in read
    s = self.fileobj.read1(size)
OSError: [Errno 5] Input/output error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 85, in _authenticate
    new_output = self.session.read()
  File "/home/fouine/.local/lib/python3.8/site-packages/scrapli/transport/ptyprocess.py", line 381, in read
    raise EOFError("End Of File (EOF). Exception style platform.")
EOFError: End Of File (EOF). Exception style platform.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir_scrapli/tasks/netconf_edit_config.py", line 27, in netconf_edit_config
    scrapli_conn = task.host.get_connection("scrapli_netconf", task.nornir.config)
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/inventory.py", line 440, in get_connection
    self.open_connection(
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/inventory.py", line 492, in open_connection
    conn_obj.open(
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir_scrapli/connection.py", line 157, in open
    connection.open()
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/driver/driver.py", line 55, in open
    login_bytes = self.transport.open_netconf()
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 35, in open_netconf
    login_bytes = self._open_netconf_pty()
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 59, in _open_netconf_pty
    login_bytes: bytes = self._authenticate()
  File "/home/fouine/.local/lib/python3.8/site-packages/scrapli/decorators.py", line 113, in decorate
    return self.multiprocessing_timeout(
  File "/home/fouine/.local/lib/python3.8/site-packages/scrapli/decorators.py", line 301, in multiprocessing_timeout
    result = future.get(timeout=self.timeout_duration)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 97, in _authenticate
    raise ScrapliAuthenticationFailed(msg) from exc
scrapli.exceptions.ScrapliAuthenticationFailed: Failed to open connection to host PE02LT2. Do you need to disable `auth_strict_key`?

2020-10-14 16:34:17,267 -  nornir.core -     INFO -        run() - Running task 'port_cfg_xml_generation' with args {'svc_dict': {'svc': {'service': {'type': 'L2V', 'class': 'TST', 'descr': 'Ansible', 'svc_id': 500013}, 'attach_circuit_wan': [{'hostname': 'PE01LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'dot1q', 'mtu': '9212', 'vlan': '12', 'sap_descr': 'Automation', 'qos': 'BE', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE01LT2', 'port': '1/2/11', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'qinq', 'mtu': '9212', 'vlan': '100.*', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE02LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'null', 'mtu': '9212', 'vlan': '', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}]}}, 'attr_dict': {'pe': {'loopback': {'PE01LT2': {'id': 1}, 'PE02LT2': {'id': 2}}, 'qos': {'BE': {'fprdgrp': 'dc-vxlan-be', 'qos_id': 1, 'queue_id': 1}, 'AF': {'fprdgrp': 'dc-vxlan-af', 'qos_id': 6003, 'queue_id': 3}, 'EF': {'fprdgrp': 'dc-vxlan-ef', 'qos_id': 6001, 'queue_id': 6}, 'H1': {'fprdgrp': 'dc-vxlan-h1', 'qos_id': 6000, 'queue_id': 7}}}}} on 2 hosts
2020-10-14 16:34:17,279 -  nornir.core -     INFO -        run() - Running task 'svc_cfg_xml_generation' with args {'svc_dict': {'svc': {'service': {'type': 'L2V', 'class': 'TST', 'descr': 'Ansible', 'svc_id': 500013}, 'attach_circuit_wan': [{'hostname': 'PE01LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'dot1q', 'mtu': '9212', 'vlan': '12', 'sap_descr': 'Automation', 'qos': 'BE', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE01LT2', 'port': '1/2/11', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'qinq', 'mtu': '9212', 'vlan': '100.*', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE02LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'null', 'mtu': '9212', 'vlan': '', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}]}}, 'attr_dict': {'pe': {'loopback': {'PE01LT2': {'id': 1}, 'PE02LT2': {'id': 2}}, 'qos': {'BE': {'fprdgrp': 'dc-vxlan-be', 'qos_id': 1, 'queue_id': 1}, 'AF': {'fprdgrp': 'dc-vxlan-af', 'qos_id': 6003, 'queue_id': 3}, 'EF': {'fprdgrp': 'dc-vxlan-ef', 'qos_id': 6001, 'queue_id': 6}, 'H1': {'fprdgrp': 'dc-vxlan-h1', 'qos_id': 6000, 'queue_id': 7}}}}} on 2 hosts
2020-10-14 16:34:17,289 -  nornir.core -     INFO -        run() - Running task 'sap_cfg_xml_generation' with args {'svc_dict': {'svc': {'service': {'type': 'L2V', 'class': 'TST', 'descr': 'Ansible', 'svc_id': 500013}, 'attach_circuit_wan': [{'hostname': 'PE01LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'dot1q', 'mtu': '9212', 'vlan': '12', 'sap_descr': 'Automation', 'qos': 'BE', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE01LT2', 'port': '1/2/11', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'qinq', 'mtu': '9212', 'vlan': '100.*', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE02LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'null', 'mtu': '9212', 'vlan': '', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}]}}, 'attr_dict': {'pe': {'loopback': {'PE01LT2': {'id': 1}, 'PE02LT2': {'id': 2}}, 'qos': {'BE': {'fprdgrp': 'dc-vxlan-be', 'qos_id': 1, 'queue_id': 1}, 'AF': {'fprdgrp': 'dc-vxlan-af', 'qos_id': 6003, 'queue_id': 3}, 'EF': {'fprdgrp': 'dc-vxlan-ef', 'qos_id': 6001, 'queue_id': 6}, 'H1': {'fprdgrp': 'dc-vxlan-h1', 'qos_id': 6000, 'queue_id': 7}}}}} on 2 hosts
2020-10-14 16:34:17,305 -  nornir.core -     INFO -        run() - Running task 'full_cfg_xml_generation' with args {'svc_dict': {'svc': {'service': {'type': 'L2V', 'class': 'TST', 'descr': 'Ansible', 'svc_id': 500013}, 'attach_circuit_wan': [{'hostname': 'PE01LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'dot1q', 'mtu': '9212', 'vlan': '12', 'sap_descr': 'Automation', 'qos': 'BE', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE01LT2', 'port': '1/2/11', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'qinq', 'mtu': '9212', 'vlan': '100.*', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE02LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'null', 'mtu': '9212', 'vlan': '', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}]}}} on 2 hosts
2020-10-14 16:34:17,316 -  nornir.core -     INFO -        run() - Running task 'send_xml_payload' with args {} on 2 hosts
2020-10-14 16:34:18,629 - nornir.core.task -    ERROR -      start() - Host 'PE02LT2': task 'XML payload through Netconf' failed with traceback:
Traceback (most recent call last):
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir_scrapli/tasks/netconf_edit_config.py", line 27, in netconf_edit_config
    scrapli_conn = task.host.get_connection("scrapli_netconf", task.nornir.config)
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/inventory.py", line 440, in get_connection
    self.open_connection(
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/inventory.py", line 492, in open_connection
    conn_obj.open(
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir_scrapli/connection.py", line 157, in open
    connection.open()
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/driver/driver.py", line 55, in open
    login_bytes = self.transport.open_netconf()
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 35, in open_netconf
    login_bytes = self._open_netconf_pty()
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 59, in _open_netconf_pty
    login_bytes: bytes = self._authenticate()
  File "/home/fouine/.local/lib/python3.8/site-packages/scrapli/decorators.py", line 113, in decorate
    return self.multiprocessing_timeout(
  File "/home/fouine/.local/lib/python3.8/site-packages/scrapli/decorators.py", line 301, in multiprocessing_timeout
    result = future.get(timeout=self.timeout_duration)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 111, in _authenticate
    raise ScrapliAuthenticationFailed(msg)
scrapli.exceptions.ScrapliAuthenticationFailed: `password` seen multiple times during session establishment, likely failed authentication

2020-10-14 16:34:18,629 - nornir.core.task -    ERROR -      start() - Host 'PE01LT2': task 'XML payload through Netconf' failed with traceback:
Traceback (most recent call last):
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir_scrapli/tasks/netconf_edit_config.py", line 27, in netconf_edit_config
    scrapli_conn = task.host.get_connection("scrapli_netconf", task.nornir.config)
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/inventory.py", line 440, in get_connection
    self.open_connection(
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/inventory.py", line 492, in open_connection
    conn_obj.open(
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir_scrapli/connection.py", line 157, in open
    connection.open()
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/driver/driver.py", line 55, in open
    login_bytes = self.transport.open_netconf()
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 35, in open_netconf
    login_bytes = self._open_netconf_pty()
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 59, in _open_netconf_pty
    login_bytes: bytes = self._authenticate()
  File "/home/fouine/.local/lib/python3.8/site-packages/scrapli/decorators.py", line 113, in decorate
    return self.multiprocessing_timeout(
  File "/home/fouine/.local/lib/python3.8/site-packages/scrapli/decorators.py", line 301, in multiprocessing_timeout
    result = future.get(timeout=self.timeout_duration)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 111, in _authenticate
    raise ScrapliAuthenticationFailed(msg)
scrapli.exceptions.ScrapliAuthenticationFailed: `password` seen multiple times during session establishment, likely failed authentication

2020-10-14 16:37:33,903 -  nornir.core -     INFO -        run() - Running task 'port_cfg_xml_generation' with args {'svc_dict': {'svc': {'service': {'type': 'L2V', 'class': 'TST', 'descr': 'Ansible', 'svc_id': 500013}, 'attach_circuit_wan': [{'hostname': 'PE01LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'dot1q', 'mtu': '9212', 'vlan': '12', 'sap_descr': 'Automation', 'qos': 'BE', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE01LT2', 'port': '1/2/11', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'qinq', 'mtu': '9212', 'vlan': '100.*', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE02LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'null', 'mtu': '9212', 'vlan': '', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}]}}, 'attr_dict': {'pe': {'loopback': {'PE01LT2': {'id': 1}, 'PE02LT2': {'id': 2}}, 'qos': {'BE': {'fprdgrp': 'dc-vxlan-be', 'qos_id': 1, 'queue_id': 1}, 'AF': {'fprdgrp': 'dc-vxlan-af', 'qos_id': 6003, 'queue_id': 3}, 'EF': {'fprdgrp': 'dc-vxlan-ef', 'qos_id': 6001, 'queue_id': 6}, 'H1': {'fprdgrp': 'dc-vxlan-h1', 'qos_id': 6000, 'queue_id': 7}}}}} on 2 hosts
2020-10-14 16:37:33,913 -  nornir.core -     INFO -        run() - Running task 'svc_cfg_xml_generation' with args {'svc_dict': {'svc': {'service': {'type': 'L2V', 'class': 'TST', 'descr': 'Ansible', 'svc_id': 500013}, 'attach_circuit_wan': [{'hostname': 'PE01LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'dot1q', 'mtu': '9212', 'vlan': '12', 'sap_descr': 'Automation', 'qos': 'BE', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE01LT2', 'port': '1/2/11', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'qinq', 'mtu': '9212', 'vlan': '100.*', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE02LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'null', 'mtu': '9212', 'vlan': '', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}]}}, 'attr_dict': {'pe': {'loopback': {'PE01LT2': {'id': 1}, 'PE02LT2': {'id': 2}}, 'qos': {'BE': {'fprdgrp': 'dc-vxlan-be', 'qos_id': 1, 'queue_id': 1}, 'AF': {'fprdgrp': 'dc-vxlan-af', 'qos_id': 6003, 'queue_id': 3}, 'EF': {'fprdgrp': 'dc-vxlan-ef', 'qos_id': 6001, 'queue_id': 6}, 'H1': {'fprdgrp': 'dc-vxlan-h1', 'qos_id': 6000, 'queue_id': 7}}}}} on 2 hosts
2020-10-14 16:37:33,923 -  nornir.core -     INFO -        run() - Running task 'sap_cfg_xml_generation' with args {'svc_dict': {'svc': {'service': {'type': 'L2V', 'class': 'TST', 'descr': 'Ansible', 'svc_id': 500013}, 'attach_circuit_wan': [{'hostname': 'PE01LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'dot1q', 'mtu': '9212', 'vlan': '12', 'sap_descr': 'Automation', 'qos': 'BE', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE01LT2', 'port': '1/2/11', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'qinq', 'mtu': '9212', 'vlan': '100.*', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE02LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'null', 'mtu': '9212', 'vlan': '', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}]}}, 'attr_dict': {'pe': {'loopback': {'PE01LT2': {'id': 1}, 'PE02LT2': {'id': 2}}, 'qos': {'BE': {'fprdgrp': 'dc-vxlan-be', 'qos_id': 1, 'queue_id': 1}, 'AF': {'fprdgrp': 'dc-vxlan-af', 'qos_id': 6003, 'queue_id': 3}, 'EF': {'fprdgrp': 'dc-vxlan-ef', 'qos_id': 6001, 'queue_id': 6}, 'H1': {'fprdgrp': 'dc-vxlan-h1', 'qos_id': 6000, 'queue_id': 7}}}}} on 2 hosts
2020-10-14 16:37:33,937 -  nornir.core -     INFO -        run() - Running task 'full_cfg_xml_generation' with args {'svc_dict': {'svc': {'service': {'type': 'L2V', 'class': 'TST', 'descr': 'Ansible', 'svc_id': 500013}, 'attach_circuit_wan': [{'hostname': 'PE01LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'dot1q', 'mtu': '9212', 'vlan': '12', 'sap_descr': 'Automation', 'qos': 'BE', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE01LT2', 'port': '1/2/11', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'qinq', 'mtu': '9212', 'vlan': '100.*', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE02LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'null', 'mtu': '9212', 'vlan': '', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}]}}} on 2 hosts
2020-10-14 16:37:33,950 -  nornir.core -     INFO -        run() - Running task 'device_config' with args {'svc_dict': {'svc': {'service': {'type': 'L2V', 'class': 'TST', 'descr': 'Ansible', 'svc_id': 500013}, 'attach_circuit_wan': [{'hostname': 'PE01LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'dot1q', 'mtu': '9212', 'vlan': '12', 'sap_descr': 'Automation', 'qos': 'BE', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE01LT2', 'port': '1/2/11', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'qinq', 'mtu': '9212', 'vlan': '100.*', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE02LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'null', 'mtu': '9212', 'vlan': '', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}]}}, 'attr_dict': {'pe': {'loopback': {'PE01LT2': {'id': 1}, 'PE02LT2': {'id': 2}}, 'qos': {'BE': {'fprdgrp': 'dc-vxlan-be', 'qos_id': 1, 'queue_id': 1}, 'AF': {'fprdgrp': 'dc-vxlan-af', 'qos_id': 6003, 'queue_id': 3}, 'EF': {'fprdgrp': 'dc-vxlan-ef', 'qos_id': 6001, 'queue_id': 6}, 'H1': {'fprdgrp': 'dc-vxlan-h1', 'qos_id': 6000, 'queue_id': 7}}}}} on 2 hosts
2020-10-14 16:37:35,249 - nornir.core.task -    ERROR -      start() - Host 'PE02LT2': task 'netconf_edit_config' failed with traceback:
Traceback (most recent call last):
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir_scrapli/tasks/netconf_edit_config.py", line 27, in netconf_edit_config
    scrapli_conn = task.host.get_connection("scrapli_netconf", task.nornir.config)
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/inventory.py", line 440, in get_connection
    self.open_connection(
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/inventory.py", line 492, in open_connection
    conn_obj.open(
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir_scrapli/connection.py", line 157, in open
    connection.open()
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/driver/driver.py", line 55, in open
    login_bytes = self.transport.open_netconf()
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 35, in open_netconf
    login_bytes = self._open_netconf_pty()
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 59, in _open_netconf_pty
    login_bytes: bytes = self._authenticate()
  File "/home/fouine/.local/lib/python3.8/site-packages/scrapli/decorators.py", line 113, in decorate
    return self.multiprocessing_timeout(
  File "/home/fouine/.local/lib/python3.8/site-packages/scrapli/decorators.py", line 301, in multiprocessing_timeout
    result = future.get(timeout=self.timeout_duration)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 111, in _authenticate
    raise ScrapliAuthenticationFailed(msg)
scrapli.exceptions.ScrapliAuthenticationFailed: `password` seen multiple times during session establishment, likely failed authentication

2020-10-14 16:37:35,254 - nornir.core.task -    ERROR -      start() - Host 'PE02LT2': task 'device_config' failed with traceback:
Traceback (most recent call last):
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/mnt/c/Users/j.corsini/Documents/python_scripts/trials_automation/python_scripts/scrapli/netconf_through_scrapli.py", line 77, in device_config
    task.run(task=netconf_edit_config, config=payload)
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/task.py", line 168, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: netconf_edit_config (failed)


2020-10-14 16:37:35,260 - nornir.core.task -    ERROR -      start() - Host 'PE01LT2': task 'netconf_edit_config' failed with traceback:
Traceback (most recent call last):
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir_scrapli/tasks/netconf_edit_config.py", line 27, in netconf_edit_config
    scrapli_conn = task.host.get_connection("scrapli_netconf", task.nornir.config)
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/inventory.py", line 440, in get_connection
    self.open_connection(
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/inventory.py", line 492, in open_connection
    conn_obj.open(
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir_scrapli/connection.py", line 157, in open
    connection.open()
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/driver/driver.py", line 55, in open
    login_bytes = self.transport.open_netconf()
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 35, in open_netconf
    login_bytes = self._open_netconf_pty()
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 59, in _open_netconf_pty
    login_bytes: bytes = self._authenticate()
  File "/home/fouine/.local/lib/python3.8/site-packages/scrapli/decorators.py", line 113, in decorate
    return self.multiprocessing_timeout(
  File "/home/fouine/.local/lib/python3.8/site-packages/scrapli/decorators.py", line 301, in multiprocessing_timeout
    result = future.get(timeout=self.timeout_duration)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 111, in _authenticate
    raise ScrapliAuthenticationFailed(msg)
scrapli.exceptions.ScrapliAuthenticationFailed: `password` seen multiple times during session establishment, likely failed authentication

2020-10-14 16:37:35,261 - nornir.core.task -    ERROR -      start() - Host 'PE01LT2': task 'device_config' failed with traceback:
Traceback (most recent call last):
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/mnt/c/Users/j.corsini/Documents/python_scripts/trials_automation/python_scripts/scrapli/netconf_through_scrapli.py", line 77, in device_config
    task.run(task=netconf_edit_config, config=payload)
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/task.py", line 168, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: netconf_edit_config (failed)


2020-10-14 16:38:39,751 -  nornir.core -     INFO -        run() - Running task 'port_cfg_xml_generation' with args {'svc_dict': {'svc': {'service': {'type': 'L2V', 'class': 'TST', 'descr': 'Ansible', 'svc_id': 500013}, 'attach_circuit_wan': [{'hostname': 'PE01LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'dot1q', 'mtu': '9212', 'vlan': '12', 'sap_descr': 'Automation', 'qos': 'BE', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE01LT2', 'port': '1/2/11', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'qinq', 'mtu': '9212', 'vlan': '100.*', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE02LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'null', 'mtu': '9212', 'vlan': '', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}]}}, 'attr_dict': {'pe': {'loopback': {'PE01LT2': {'id': 1}, 'PE02LT2': {'id': 2}}, 'qos': {'BE': {'fprdgrp': 'dc-vxlan-be', 'qos_id': 1, 'queue_id': 1}, 'AF': {'fprdgrp': 'dc-vxlan-af', 'qos_id': 6003, 'queue_id': 3}, 'EF': {'fprdgrp': 'dc-vxlan-ef', 'qos_id': 6001, 'queue_id': 6}, 'H1': {'fprdgrp': 'dc-vxlan-h1', 'qos_id': 6000, 'queue_id': 7}}}}} on 2 hosts
2020-10-14 16:38:39,761 -  nornir.core -     INFO -        run() - Running task 'svc_cfg_xml_generation' with args {'svc_dict': {'svc': {'service': {'type': 'L2V', 'class': 'TST', 'descr': 'Ansible', 'svc_id': 500013}, 'attach_circuit_wan': [{'hostname': 'PE01LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'dot1q', 'mtu': '9212', 'vlan': '12', 'sap_descr': 'Automation', 'qos': 'BE', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE01LT2', 'port': '1/2/11', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'qinq', 'mtu': '9212', 'vlan': '100.*', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE02LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'null', 'mtu': '9212', 'vlan': '', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}]}}, 'attr_dict': {'pe': {'loopback': {'PE01LT2': {'id': 1}, 'PE02LT2': {'id': 2}}, 'qos': {'BE': {'fprdgrp': 'dc-vxlan-be', 'qos_id': 1, 'queue_id': 1}, 'AF': {'fprdgrp': 'dc-vxlan-af', 'qos_id': 6003, 'queue_id': 3}, 'EF': {'fprdgrp': 'dc-vxlan-ef', 'qos_id': 6001, 'queue_id': 6}, 'H1': {'fprdgrp': 'dc-vxlan-h1', 'qos_id': 6000, 'queue_id': 7}}}}} on 2 hosts
2020-10-14 16:38:39,772 -  nornir.core -     INFO -        run() - Running task 'sap_cfg_xml_generation' with args {'svc_dict': {'svc': {'service': {'type': 'L2V', 'class': 'TST', 'descr': 'Ansible', 'svc_id': 500013}, 'attach_circuit_wan': [{'hostname': 'PE01LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'dot1q', 'mtu': '9212', 'vlan': '12', 'sap_descr': 'Automation', 'qos': 'BE', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE01LT2', 'port': '1/2/11', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'qinq', 'mtu': '9212', 'vlan': '100.*', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE02LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'null', 'mtu': '9212', 'vlan': '', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}]}}, 'attr_dict': {'pe': {'loopback': {'PE01LT2': {'id': 1}, 'PE02LT2': {'id': 2}}, 'qos': {'BE': {'fprdgrp': 'dc-vxlan-be', 'qos_id': 1, 'queue_id': 1}, 'AF': {'fprdgrp': 'dc-vxlan-af', 'qos_id': 6003, 'queue_id': 3}, 'EF': {'fprdgrp': 'dc-vxlan-ef', 'qos_id': 6001, 'queue_id': 6}, 'H1': {'fprdgrp': 'dc-vxlan-h1', 'qos_id': 6000, 'queue_id': 7}}}}} on 2 hosts
2020-10-14 16:38:39,787 -  nornir.core -     INFO -        run() - Running task 'full_cfg_xml_generation' with args {'svc_dict': {'svc': {'service': {'type': 'L2V', 'class': 'TST', 'descr': 'Ansible', 'svc_id': 500013}, 'attach_circuit_wan': [{'hostname': 'PE01LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'dot1q', 'mtu': '9212', 'vlan': '12', 'sap_descr': 'Automation', 'qos': 'BE', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE01LT2', 'port': '1/2/11', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'qinq', 'mtu': '9212', 'vlan': '100.*', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE02LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'null', 'mtu': '9212', 'vlan': '', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}]}}} on 2 hosts
2020-10-14 16:38:39,798 -  nornir.core -     INFO -        run() - Running task 'send_xml_payload' with args {} on 2 hosts
2020-10-14 16:38:40,643 - nornir.core.task -    ERROR -      start() - Host 'PE02LT2': task 'XML payload through Netconf' failed with traceback:
Traceback (most recent call last):
  File "/home/fouine/.local/lib/python3.8/site-packages/scrapli/transport/ptyprocess.py", line 376, in read
    s = self.fileobj.read1(size)
OSError: [Errno 5] Input/output error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 85, in _authenticate
    new_output = self.session.read()
  File "/home/fouine/.local/lib/python3.8/site-packages/scrapli/transport/ptyprocess.py", line 381, in read
    raise EOFError("End Of File (EOF). Exception style platform.")
EOFError: End Of File (EOF). Exception style platform.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir_scrapli/tasks/netconf_edit_config.py", line 27, in netconf_edit_config
    scrapli_conn = task.host.get_connection("scrapli_netconf", task.nornir.config)
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/inventory.py", line 440, in get_connection
    self.open_connection(
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/inventory.py", line 492, in open_connection
    conn_obj.open(
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir_scrapli/connection.py", line 157, in open
    connection.open()
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/driver/driver.py", line 55, in open
    login_bytes = self.transport.open_netconf()
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 35, in open_netconf
    login_bytes = self._open_netconf_pty()
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 59, in _open_netconf_pty
    login_bytes: bytes = self._authenticate()
  File "/home/fouine/.local/lib/python3.8/site-packages/scrapli/decorators.py", line 113, in decorate
    return self.multiprocessing_timeout(
  File "/home/fouine/.local/lib/python3.8/site-packages/scrapli/decorators.py", line 301, in multiprocessing_timeout
    result = future.get(timeout=self.timeout_duration)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 97, in _authenticate
    raise ScrapliAuthenticationFailed(msg) from exc
scrapli.exceptions.ScrapliAuthenticationFailed: Failed to open connection to host PE02LT2. Do you need to disable `auth_strict_key`?

2020-10-14 16:38:40,645 - nornir.core.task -    ERROR -      start() - Host 'PE01LT2': task 'XML payload through Netconf' failed with traceback:
Traceback (most recent call last):
  File "/home/fouine/.local/lib/python3.8/site-packages/scrapli/transport/ptyprocess.py", line 376, in read
    s = self.fileobj.read1(size)
OSError: [Errno 5] Input/output error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 85, in _authenticate
    new_output = self.session.read()
  File "/home/fouine/.local/lib/python3.8/site-packages/scrapli/transport/ptyprocess.py", line 381, in read
    raise EOFError("End Of File (EOF). Exception style platform.")
EOFError: End Of File (EOF). Exception style platform.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir_scrapli/tasks/netconf_edit_config.py", line 27, in netconf_edit_config
    scrapli_conn = task.host.get_connection("scrapli_netconf", task.nornir.config)
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/inventory.py", line 440, in get_connection
    self.open_connection(
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/inventory.py", line 492, in open_connection
    conn_obj.open(
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir_scrapli/connection.py", line 157, in open
    connection.open()
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/driver/driver.py", line 55, in open
    login_bytes = self.transport.open_netconf()
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 35, in open_netconf
    login_bytes = self._open_netconf_pty()
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 59, in _open_netconf_pty
    login_bytes: bytes = self._authenticate()
  File "/home/fouine/.local/lib/python3.8/site-packages/scrapli/decorators.py", line 113, in decorate
    return self.multiprocessing_timeout(
  File "/home/fouine/.local/lib/python3.8/site-packages/scrapli/decorators.py", line 301, in multiprocessing_timeout
    result = future.get(timeout=self.timeout_duration)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 97, in _authenticate
    raise ScrapliAuthenticationFailed(msg) from exc
scrapli.exceptions.ScrapliAuthenticationFailed: Failed to open connection to host PE01LT2. Do you need to disable `auth_strict_key`?

2020-10-14 16:40:30,183 -  nornir.core -     INFO -        run() - Running task 'device_config' with args {'svc_dict': {'svc': {'service': {'type': 'L2V', 'class': 'TST', 'descr': 'Ansible', 'svc_id': 500013}, 'attach_circuit_wan': [{'hostname': 'PE01LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'dot1q', 'mtu': '9212', 'vlan': '12', 'sap_descr': 'Automation', 'qos': 'BE', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE01LT2', 'port': '1/2/11', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'qinq', 'mtu': '9212', 'vlan': '100.*', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE02LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'null', 'mtu': '9212', 'vlan': '', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}]}}, 'attr_dict': {'pe': {'loopback': {'PE01LT2': {'id': 1}, 'PE02LT2': {'id': 2}}, 'qos': {'BE': {'fprdgrp': 'dc-vxlan-be', 'qos_id': 1, 'queue_id': 1}, 'AF': {'fprdgrp': 'dc-vxlan-af', 'qos_id': 6003, 'queue_id': 3}, 'EF': {'fprdgrp': 'dc-vxlan-ef', 'qos_id': 6001, 'queue_id': 6}, 'H1': {'fprdgrp': 'dc-vxlan-h1', 'qos_id': 6000, 'queue_id': 7}}}}} on 2 hosts
2020-10-14 16:40:31,038 - nornir.core.task -    ERROR -      start() - Host 'PE01LT2': task 'netconf_edit_config' failed with traceback:
Traceback (most recent call last):
  File "/home/fouine/.local/lib/python3.8/site-packages/scrapli/transport/ptyprocess.py", line 376, in read
    s = self.fileobj.read1(size)
OSError: [Errno 5] Input/output error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 85, in _authenticate
    new_output = self.session.read()
  File "/home/fouine/.local/lib/python3.8/site-packages/scrapli/transport/ptyprocess.py", line 381, in read
    raise EOFError("End Of File (EOF). Exception style platform.")
EOFError: End Of File (EOF). Exception style platform.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir_scrapli/tasks/netconf_edit_config.py", line 27, in netconf_edit_config
    scrapli_conn = task.host.get_connection("scrapli_netconf", task.nornir.config)
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/inventory.py", line 440, in get_connection
    self.open_connection(
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/inventory.py", line 492, in open_connection
    conn_obj.open(
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir_scrapli/connection.py", line 157, in open
    connection.open()
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/driver/driver.py", line 55, in open
    login_bytes = self.transport.open_netconf()
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 35, in open_netconf
    login_bytes = self._open_netconf_pty()
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 59, in _open_netconf_pty
    login_bytes: bytes = self._authenticate()
  File "/home/fouine/.local/lib/python3.8/site-packages/scrapli/decorators.py", line 113, in decorate
    return self.multiprocessing_timeout(
  File "/home/fouine/.local/lib/python3.8/site-packages/scrapli/decorators.py", line 301, in multiprocessing_timeout
    result = future.get(timeout=self.timeout_duration)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 97, in _authenticate
    raise ScrapliAuthenticationFailed(msg) from exc
scrapli.exceptions.ScrapliAuthenticationFailed: Failed to open connection to host PE01LT2. Do you need to disable `auth_strict_key`?

2020-10-14 16:40:31,041 - nornir.core.task -    ERROR -      start() - Host 'PE02LT2': task 'netconf_edit_config' failed with traceback:
Traceback (most recent call last):
  File "/home/fouine/.local/lib/python3.8/site-packages/scrapli/transport/ptyprocess.py", line 376, in read
    s = self.fileobj.read1(size)
OSError: [Errno 5] Input/output error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 85, in _authenticate
    new_output = self.session.read()
  File "/home/fouine/.local/lib/python3.8/site-packages/scrapli/transport/ptyprocess.py", line 381, in read
    raise EOFError("End Of File (EOF). Exception style platform.")
EOFError: End Of File (EOF). Exception style platform.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir_scrapli/tasks/netconf_edit_config.py", line 27, in netconf_edit_config
    scrapli_conn = task.host.get_connection("scrapli_netconf", task.nornir.config)
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/inventory.py", line 440, in get_connection
    self.open_connection(
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/inventory.py", line 492, in open_connection
    conn_obj.open(
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir_scrapli/connection.py", line 157, in open
    connection.open()
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/driver/driver.py", line 55, in open
    login_bytes = self.transport.open_netconf()
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 35, in open_netconf
    login_bytes = self._open_netconf_pty()
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 59, in _open_netconf_pty
    login_bytes: bytes = self._authenticate()
  File "/home/fouine/.local/lib/python3.8/site-packages/scrapli/decorators.py", line 113, in decorate
    return self.multiprocessing_timeout(
  File "/home/fouine/.local/lib/python3.8/site-packages/scrapli/decorators.py", line 301, in multiprocessing_timeout
    result = future.get(timeout=self.timeout_duration)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 97, in _authenticate
    raise ScrapliAuthenticationFailed(msg) from exc
scrapli.exceptions.ScrapliAuthenticationFailed: Failed to open connection to host PE02LT2. Do you need to disable `auth_strict_key`?

2020-10-14 16:40:31,044 - nornir.core.task -    ERROR -      start() - Host 'PE01LT2': task 'device_config' failed with traceback:
Traceback (most recent call last):
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/mnt/c/Users/j.corsini/Documents/python_scripts/trials_automation/python_scripts/scrapli/test.py", line 14, in device_config
    task.run(task=netconf_edit_config, config=payload)
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/task.py", line 168, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: netconf_edit_config (failed)


2020-10-14 16:40:31,044 - nornir.core.task -    ERROR -      start() - Host 'PE02LT2': task 'device_config' failed with traceback:
Traceback (most recent call last):
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/mnt/c/Users/j.corsini/Documents/python_scripts/trials_automation/python_scripts/scrapli/test.py", line 14, in device_config
    task.run(task=netconf_edit_config, config=payload)
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/task.py", line 168, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: netconf_edit_config (failed)


2020-10-14 16:42:37,026 -  nornir.core -     INFO -        run() - Running task 'device_config' with args {'svc_dict': {'svc': {'service': {'type': 'L2V', 'class': 'TST', 'descr': 'Ansible', 'svc_id': 500013}, 'attach_circuit_wan': [{'hostname': 'PE01LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'dot1q', 'mtu': '9212', 'vlan': '12', 'sap_descr': 'Automation', 'qos': 'BE', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE01LT2', 'port': '1/2/11', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'qinq', 'mtu': '9212', 'vlan': '100.*', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE02LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'null', 'mtu': '9212', 'vlan': '', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}]}}, 'attr_dict': {'pe': {'loopback': {'PE01LT2': {'id': 1}, 'PE02LT2': {'id': 2}}, 'qos': {'BE': {'fprdgrp': 'dc-vxlan-be', 'qos_id': 1, 'queue_id': 1}, 'AF': {'fprdgrp': 'dc-vxlan-af', 'qos_id': 6003, 'queue_id': 3}, 'EF': {'fprdgrp': 'dc-vxlan-ef', 'qos_id': 6001, 'queue_id': 6}, 'H1': {'fprdgrp': 'dc-vxlan-h1', 'qos_id': 6000, 'queue_id': 7}}}}} on 2 hosts
2020-10-14 16:42:37,833 - nornir.core.task -    ERROR -      start() - Host 'PE02LT2': task 'netconf_edit_config' failed with traceback:
Traceback (most recent call last):
  File "/home/fouine/.local/lib/python3.8/site-packages/scrapli/transport/ptyprocess.py", line 376, in read
    s = self.fileobj.read1(size)
OSError: [Errno 5] Input/output error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 85, in _authenticate
    new_output = self.session.read()
  File "/home/fouine/.local/lib/python3.8/site-packages/scrapli/transport/ptyprocess.py", line 381, in read
    raise EOFError("End Of File (EOF). Exception style platform.")
EOFError: End Of File (EOF). Exception style platform.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir_scrapli/tasks/netconf_edit_config.py", line 27, in netconf_edit_config
    scrapli_conn = task.host.get_connection("scrapli_netconf", task.nornir.config)
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/inventory.py", line 440, in get_connection
    self.open_connection(
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/inventory.py", line 492, in open_connection
    conn_obj.open(
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir_scrapli/connection.py", line 157, in open
    connection.open()
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/driver/driver.py", line 55, in open
    login_bytes = self.transport.open_netconf()
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 35, in open_netconf
    login_bytes = self._open_netconf_pty()
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 59, in _open_netconf_pty
    login_bytes: bytes = self._authenticate()
  File "/home/fouine/.local/lib/python3.8/site-packages/scrapli/decorators.py", line 113, in decorate
    return self.multiprocessing_timeout(
  File "/home/fouine/.local/lib/python3.8/site-packages/scrapli/decorators.py", line 301, in multiprocessing_timeout
    result = future.get(timeout=self.timeout_duration)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 97, in _authenticate
    raise ScrapliAuthenticationFailed(msg) from exc
scrapli.exceptions.ScrapliAuthenticationFailed: Failed to open connection to host PE02LT2. Do you need to disable `auth_strict_key`?

2020-10-14 16:42:37,834 - nornir.core.task -    ERROR -      start() - Host 'PE01LT2': task 'netconf_edit_config' failed with traceback:
Traceback (most recent call last):
  File "/home/fouine/.local/lib/python3.8/site-packages/scrapli/transport/ptyprocess.py", line 376, in read
    s = self.fileobj.read1(size)
OSError: [Errno 5] Input/output error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 85, in _authenticate
    new_output = self.session.read()
  File "/home/fouine/.local/lib/python3.8/site-packages/scrapli/transport/ptyprocess.py", line 381, in read
    raise EOFError("End Of File (EOF). Exception style platform.")
EOFError: End Of File (EOF). Exception style platform.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir_scrapli/tasks/netconf_edit_config.py", line 27, in netconf_edit_config
    scrapli_conn = task.host.get_connection("scrapli_netconf", task.nornir.config)
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/inventory.py", line 440, in get_connection
    self.open_connection(
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/inventory.py", line 492, in open_connection
    conn_obj.open(
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir_scrapli/connection.py", line 157, in open
    connection.open()
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/driver/driver.py", line 55, in open
    login_bytes = self.transport.open_netconf()
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 35, in open_netconf
    login_bytes = self._open_netconf_pty()
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 59, in _open_netconf_pty
    login_bytes: bytes = self._authenticate()
  File "/home/fouine/.local/lib/python3.8/site-packages/scrapli/decorators.py", line 113, in decorate
    return self.multiprocessing_timeout(
  File "/home/fouine/.local/lib/python3.8/site-packages/scrapli/decorators.py", line 301, in multiprocessing_timeout
    result = future.get(timeout=self.timeout_duration)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 97, in _authenticate
    raise ScrapliAuthenticationFailed(msg) from exc
scrapli.exceptions.ScrapliAuthenticationFailed: Failed to open connection to host PE01LT2. Do you need to disable `auth_strict_key`?

2020-10-14 16:42:37,838 - nornir.core.task -    ERROR -      start() - Host 'PE01LT2': task 'device_config' failed with traceback:
Traceback (most recent call last):
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/mnt/c/Users/j.corsini/Documents/python_scripts/trials_automation/python_scripts/scrapli/test.py", line 14, in device_config
    task.run(task=netconf_edit_config, config=payload)
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/task.py", line 168, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: netconf_edit_config (failed)


2020-10-14 16:42:37,838 - nornir.core.task -    ERROR -      start() - Host 'PE02LT2': task 'device_config' failed with traceback:
Traceback (most recent call last):
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/mnt/c/Users/j.corsini/Documents/python_scripts/trials_automation/python_scripts/scrapli/test.py", line 14, in device_config
    task.run(task=netconf_edit_config, config=payload)
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/task.py", line 168, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: netconf_edit_config (failed)


2020-10-14 16:43:02,800 -  nornir.core -     INFO -        run() - Running task 'port_cfg_xml_generation' with args {'svc_dict': {'svc': {'service': {'type': 'L2V', 'class': 'TST', 'descr': 'Ansible', 'svc_id': 500013}, 'attach_circuit_wan': [{'hostname': 'PE01LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'dot1q', 'mtu': '9212', 'vlan': '12', 'sap_descr': 'Automation', 'qos': 'BE', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE01LT2', 'port': '1/2/11', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'qinq', 'mtu': '9212', 'vlan': '100.*', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE02LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'null', 'mtu': '9212', 'vlan': '', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}]}}, 'attr_dict': {'pe': {'loopback': {'PE01LT2': {'id': 1}, 'PE02LT2': {'id': 2}}, 'qos': {'BE': {'fprdgrp': 'dc-vxlan-be', 'qos_id': 1, 'queue_id': 1}, 'AF': {'fprdgrp': 'dc-vxlan-af', 'qos_id': 6003, 'queue_id': 3}, 'EF': {'fprdgrp': 'dc-vxlan-ef', 'qos_id': 6001, 'queue_id': 6}, 'H1': {'fprdgrp': 'dc-vxlan-h1', 'qos_id': 6000, 'queue_id': 7}}}}} on 2 hosts
2020-10-14 16:43:02,810 -  nornir.core -     INFO -        run() - Running task 'svc_cfg_xml_generation' with args {'svc_dict': {'svc': {'service': {'type': 'L2V', 'class': 'TST', 'descr': 'Ansible', 'svc_id': 500013}, 'attach_circuit_wan': [{'hostname': 'PE01LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'dot1q', 'mtu': '9212', 'vlan': '12', 'sap_descr': 'Automation', 'qos': 'BE', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE01LT2', 'port': '1/2/11', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'qinq', 'mtu': '9212', 'vlan': '100.*', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE02LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'null', 'mtu': '9212', 'vlan': '', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}]}}, 'attr_dict': {'pe': {'loopback': {'PE01LT2': {'id': 1}, 'PE02LT2': {'id': 2}}, 'qos': {'BE': {'fprdgrp': 'dc-vxlan-be', 'qos_id': 1, 'queue_id': 1}, 'AF': {'fprdgrp': 'dc-vxlan-af', 'qos_id': 6003, 'queue_id': 3}, 'EF': {'fprdgrp': 'dc-vxlan-ef', 'qos_id': 6001, 'queue_id': 6}, 'H1': {'fprdgrp': 'dc-vxlan-h1', 'qos_id': 6000, 'queue_id': 7}}}}} on 2 hosts
2020-10-14 16:43:02,821 -  nornir.core -     INFO -        run() - Running task 'sap_cfg_xml_generation' with args {'svc_dict': {'svc': {'service': {'type': 'L2V', 'class': 'TST', 'descr': 'Ansible', 'svc_id': 500013}, 'attach_circuit_wan': [{'hostname': 'PE01LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'dot1q', 'mtu': '9212', 'vlan': '12', 'sap_descr': 'Automation', 'qos': 'BE', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE01LT2', 'port': '1/2/11', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'qinq', 'mtu': '9212', 'vlan': '100.*', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE02LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'null', 'mtu': '9212', 'vlan': '', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}]}}, 'attr_dict': {'pe': {'loopback': {'PE01LT2': {'id': 1}, 'PE02LT2': {'id': 2}}, 'qos': {'BE': {'fprdgrp': 'dc-vxlan-be', 'qos_id': 1, 'queue_id': 1}, 'AF': {'fprdgrp': 'dc-vxlan-af', 'qos_id': 6003, 'queue_id': 3}, 'EF': {'fprdgrp': 'dc-vxlan-ef', 'qos_id': 6001, 'queue_id': 6}, 'H1': {'fprdgrp': 'dc-vxlan-h1', 'qos_id': 6000, 'queue_id': 7}}}}} on 2 hosts
2020-10-14 16:43:02,837 -  nornir.core -     INFO -        run() - Running task 'full_cfg_xml_generation' with args {'svc_dict': {'svc': {'service': {'type': 'L2V', 'class': 'TST', 'descr': 'Ansible', 'svc_id': 500013}, 'attach_circuit_wan': [{'hostname': 'PE01LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'dot1q', 'mtu': '9212', 'vlan': '12', 'sap_descr': 'Automation', 'qos': 'BE', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE01LT2', 'port': '1/2/11', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'qinq', 'mtu': '9212', 'vlan': '100.*', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE02LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'null', 'mtu': '9212', 'vlan': '', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}]}}} on 2 hosts
2020-10-14 16:43:02,849 -  nornir.core -     INFO -        run() - Running task 'send_xml_payload' with args {} on 2 hosts
2020-10-14 16:43:03,849 - nornir.core.task -    ERROR -      start() - Host 'PE01LT2': task 'XML payload through Netconf' failed with traceback:
Traceback (most recent call last):
  File "/home/fouine/.local/lib/python3.8/site-packages/scrapli/transport/ptyprocess.py", line 376, in read
    s = self.fileobj.read1(size)
OSError: [Errno 5] Input/output error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 85, in _authenticate
    new_output = self.session.read()
  File "/home/fouine/.local/lib/python3.8/site-packages/scrapli/transport/ptyprocess.py", line 381, in read
    raise EOFError("End Of File (EOF). Exception style platform.")
EOFError: End Of File (EOF). Exception style platform.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir_scrapli/tasks/netconf_edit_config.py", line 27, in netconf_edit_config
    scrapli_conn = task.host.get_connection("scrapli_netconf", task.nornir.config)
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/inventory.py", line 440, in get_connection
    self.open_connection(
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/inventory.py", line 492, in open_connection
    conn_obj.open(
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir_scrapli/connection.py", line 157, in open
    connection.open()
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/driver/driver.py", line 55, in open
    login_bytes = self.transport.open_netconf()
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 35, in open_netconf
    login_bytes = self._open_netconf_pty()
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 59, in _open_netconf_pty
    login_bytes: bytes = self._authenticate()
  File "/home/fouine/.local/lib/python3.8/site-packages/scrapli/decorators.py", line 113, in decorate
    return self.multiprocessing_timeout(
  File "/home/fouine/.local/lib/python3.8/site-packages/scrapli/decorators.py", line 301, in multiprocessing_timeout
    result = future.get(timeout=self.timeout_duration)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 97, in _authenticate
    raise ScrapliAuthenticationFailed(msg) from exc
scrapli.exceptions.ScrapliAuthenticationFailed: Failed to open connection to host PE01LT2. Do you need to disable `auth_strict_key`?

2020-10-14 16:43:03,851 - nornir.core.task -    ERROR -      start() - Host 'PE02LT2': task 'XML payload through Netconf' failed with traceback:
Traceback (most recent call last):
  File "/home/fouine/.local/lib/python3.8/site-packages/scrapli/transport/ptyprocess.py", line 376, in read
    s = self.fileobj.read1(size)
OSError: [Errno 5] Input/output error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 85, in _authenticate
    new_output = self.session.read()
  File "/home/fouine/.local/lib/python3.8/site-packages/scrapli/transport/ptyprocess.py", line 381, in read
    raise EOFError("End Of File (EOF). Exception style platform.")
EOFError: End Of File (EOF). Exception style platform.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir_scrapli/tasks/netconf_edit_config.py", line 27, in netconf_edit_config
    scrapli_conn = task.host.get_connection("scrapli_netconf", task.nornir.config)
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/inventory.py", line 440, in get_connection
    self.open_connection(
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/inventory.py", line 492, in open_connection
    conn_obj.open(
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir_scrapli/connection.py", line 157, in open
    connection.open()
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/driver/driver.py", line 55, in open
    login_bytes = self.transport.open_netconf()
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 35, in open_netconf
    login_bytes = self._open_netconf_pty()
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 59, in _open_netconf_pty
    login_bytes: bytes = self._authenticate()
  File "/home/fouine/.local/lib/python3.8/site-packages/scrapli/decorators.py", line 113, in decorate
    return self.multiprocessing_timeout(
  File "/home/fouine/.local/lib/python3.8/site-packages/scrapli/decorators.py", line 301, in multiprocessing_timeout
    result = future.get(timeout=self.timeout_duration)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 97, in _authenticate
    raise ScrapliAuthenticationFailed(msg) from exc
scrapli.exceptions.ScrapliAuthenticationFailed: Failed to open connection to host PE02LT2. Do you need to disable `auth_strict_key`?

2020-10-14 16:48:04,282 -  nornir.core -     INFO -        run() - Running task 'port_cfg_xml_generation' with args {'svc_dict': {'svc': {'service': {'type': 'L2V', 'class': 'TST', 'descr': 'Ansible', 'svc_id': 500013}, 'attach_circuit_wan': [{'hostname': 'PE01LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'dot1q', 'mtu': '9212', 'vlan': '12', 'sap_descr': 'Automation', 'qos': 'BE', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE01LT2', 'port': '1/2/11', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'qinq', 'mtu': '9212', 'vlan': '100.*', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE02LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'null', 'mtu': '9212', 'vlan': '', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}]}}, 'attr_dict': {'pe': {'loopback': {'PE01LT2': {'id': 1}, 'PE02LT2': {'id': 2}}, 'qos': {'BE': {'fprdgrp': 'dc-vxlan-be', 'qos_id': 1, 'queue_id': 1}, 'AF': {'fprdgrp': 'dc-vxlan-af', 'qos_id': 6003, 'queue_id': 3}, 'EF': {'fprdgrp': 'dc-vxlan-ef', 'qos_id': 6001, 'queue_id': 6}, 'H1': {'fprdgrp': 'dc-vxlan-h1', 'qos_id': 6000, 'queue_id': 7}}}}} on 2 hosts
2020-10-14 16:48:04,292 -  nornir.core -     INFO -        run() - Running task 'svc_cfg_xml_generation' with args {'svc_dict': {'svc': {'service': {'type': 'L2V', 'class': 'TST', 'descr': 'Ansible', 'svc_id': 500013}, 'attach_circuit_wan': [{'hostname': 'PE01LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'dot1q', 'mtu': '9212', 'vlan': '12', 'sap_descr': 'Automation', 'qos': 'BE', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE01LT2', 'port': '1/2/11', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'qinq', 'mtu': '9212', 'vlan': '100.*', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE02LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'null', 'mtu': '9212', 'vlan': '', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}]}}, 'attr_dict': {'pe': {'loopback': {'PE01LT2': {'id': 1}, 'PE02LT2': {'id': 2}}, 'qos': {'BE': {'fprdgrp': 'dc-vxlan-be', 'qos_id': 1, 'queue_id': 1}, 'AF': {'fprdgrp': 'dc-vxlan-af', 'qos_id': 6003, 'queue_id': 3}, 'EF': {'fprdgrp': 'dc-vxlan-ef', 'qos_id': 6001, 'queue_id': 6}, 'H1': {'fprdgrp': 'dc-vxlan-h1', 'qos_id': 6000, 'queue_id': 7}}}}} on 2 hosts
2020-10-14 16:48:04,304 -  nornir.core -     INFO -        run() - Running task 'sap_cfg_xml_generation' with args {'svc_dict': {'svc': {'service': {'type': 'L2V', 'class': 'TST', 'descr': 'Ansible', 'svc_id': 500013}, 'attach_circuit_wan': [{'hostname': 'PE01LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'dot1q', 'mtu': '9212', 'vlan': '12', 'sap_descr': 'Automation', 'qos': 'BE', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE01LT2', 'port': '1/2/11', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'qinq', 'mtu': '9212', 'vlan': '100.*', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE02LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'null', 'mtu': '9212', 'vlan': '', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}]}}, 'attr_dict': {'pe': {'loopback': {'PE01LT2': {'id': 1}, 'PE02LT2': {'id': 2}}, 'qos': {'BE': {'fprdgrp': 'dc-vxlan-be', 'qos_id': 1, 'queue_id': 1}, 'AF': {'fprdgrp': 'dc-vxlan-af', 'qos_id': 6003, 'queue_id': 3}, 'EF': {'fprdgrp': 'dc-vxlan-ef', 'qos_id': 6001, 'queue_id': 6}, 'H1': {'fprdgrp': 'dc-vxlan-h1', 'qos_id': 6000, 'queue_id': 7}}}}} on 2 hosts
2020-10-14 16:48:04,319 -  nornir.core -     INFO -        run() - Running task 'full_cfg_xml_generation' with args {'svc_dict': {'svc': {'service': {'type': 'L2V', 'class': 'TST', 'descr': 'Ansible', 'svc_id': 500013}, 'attach_circuit_wan': [{'hostname': 'PE01LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'dot1q', 'mtu': '9212', 'vlan': '12', 'sap_descr': 'Automation', 'qos': 'BE', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE01LT2', 'port': '1/2/11', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'qinq', 'mtu': '9212', 'vlan': '100.*', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE02LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'null', 'mtu': '9212', 'vlan': '', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}]}}} on 2 hosts
2020-10-14 16:48:04,331 -  nornir.core -     INFO -        run() - Running task 'send_xml_payload' with args {} on 2 hosts
2020-10-14 16:48:05,548 - nornir.core.task -    ERROR -      start() - Host 'PE02LT2': task 'XML payload through Netconf' failed with traceback:
Traceback (most recent call last):
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir_scrapli/tasks/netconf_edit_config.py", line 27, in netconf_edit_config
    scrapli_conn = task.host.get_connection("scrapli_netconf", task.nornir.config)
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/inventory.py", line 440, in get_connection
    self.open_connection(
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/inventory.py", line 492, in open_connection
    conn_obj.open(
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir_scrapli/connection.py", line 157, in open
    connection.open()
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/driver/driver.py", line 55, in open
    login_bytes = self.transport.open_netconf()
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 35, in open_netconf
    login_bytes = self._open_netconf_pty()
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 59, in _open_netconf_pty
    login_bytes: bytes = self._authenticate()
  File "/home/fouine/.local/lib/python3.8/site-packages/scrapli/decorators.py", line 113, in decorate
    return self.multiprocessing_timeout(
  File "/home/fouine/.local/lib/python3.8/site-packages/scrapli/decorators.py", line 301, in multiprocessing_timeout
    result = future.get(timeout=self.timeout_duration)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 111, in _authenticate
    raise ScrapliAuthenticationFailed(msg)
scrapli.exceptions.ScrapliAuthenticationFailed: `password` seen multiple times during session establishment, likely failed authentication

2020-10-14 16:48:05,548 - nornir.core.task -    ERROR -      start() - Host 'PE01LT2': task 'XML payload through Netconf' failed with traceback:
Traceback (most recent call last):
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir_scrapli/tasks/netconf_edit_config.py", line 27, in netconf_edit_config
    scrapli_conn = task.host.get_connection("scrapli_netconf", task.nornir.config)
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/inventory.py", line 440, in get_connection
    self.open_connection(
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/inventory.py", line 492, in open_connection
    conn_obj.open(
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir_scrapli/connection.py", line 157, in open
    connection.open()
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/driver/driver.py", line 55, in open
    login_bytes = self.transport.open_netconf()
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 35, in open_netconf
    login_bytes = self._open_netconf_pty()
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 59, in _open_netconf_pty
    login_bytes: bytes = self._authenticate()
  File "/home/fouine/.local/lib/python3.8/site-packages/scrapli/decorators.py", line 113, in decorate
    return self.multiprocessing_timeout(
  File "/home/fouine/.local/lib/python3.8/site-packages/scrapli/decorators.py", line 301, in multiprocessing_timeout
    result = future.get(timeout=self.timeout_duration)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 111, in _authenticate
    raise ScrapliAuthenticationFailed(msg)
scrapli.exceptions.ScrapliAuthenticationFailed: `password` seen multiple times during session establishment, likely failed authentication

2020-10-14 17:08:02,708 -  nornir.core -     INFO -        run() - Running task 'port_cfg_xml_generation' with args {'svc_dict': {'svc': {'service': {'type': 'L2V', 'class': 'TST', 'descr': 'Ansible', 'svc_id': 500013}, 'attach_circuit_wan': [{'hostname': 'PE01LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'dot1q', 'mtu': '9212', 'vlan': '12', 'sap_descr': 'Automation', 'qos': 'BE', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE01LT2', 'port': '1/2/11', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'qinq', 'mtu': '9212', 'vlan': '100.*', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE02LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'null', 'mtu': '9212', 'vlan': '', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}]}}, 'attr_dict': {'pe': {'loopback': {'PE01LT2': {'id': 1}, 'PE02LT2': {'id': 2}}, 'qos': {'BE': {'fprdgrp': 'dc-vxlan-be', 'qos_id': 1, 'queue_id': 1}, 'AF': {'fprdgrp': 'dc-vxlan-af', 'qos_id': 6003, 'queue_id': 3}, 'EF': {'fprdgrp': 'dc-vxlan-ef', 'qos_id': 6001, 'queue_id': 6}, 'H1': {'fprdgrp': 'dc-vxlan-h1', 'qos_id': 6000, 'queue_id': 7}}}}} on 2 hosts
2020-10-14 17:08:02,728 -  nornir.core -     INFO -        run() - Running task 'svc_cfg_xml_generation' with args {'svc_dict': {'svc': {'service': {'type': 'L2V', 'class': 'TST', 'descr': 'Ansible', 'svc_id': 500013}, 'attach_circuit_wan': [{'hostname': 'PE01LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'dot1q', 'mtu': '9212', 'vlan': '12', 'sap_descr': 'Automation', 'qos': 'BE', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE01LT2', 'port': '1/2/11', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'qinq', 'mtu': '9212', 'vlan': '100.*', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE02LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'null', 'mtu': '9212', 'vlan': '', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}]}}, 'attr_dict': {'pe': {'loopback': {'PE01LT2': {'id': 1}, 'PE02LT2': {'id': 2}}, 'qos': {'BE': {'fprdgrp': 'dc-vxlan-be', 'qos_id': 1, 'queue_id': 1}, 'AF': {'fprdgrp': 'dc-vxlan-af', 'qos_id': 6003, 'queue_id': 3}, 'EF': {'fprdgrp': 'dc-vxlan-ef', 'qos_id': 6001, 'queue_id': 6}, 'H1': {'fprdgrp': 'dc-vxlan-h1', 'qos_id': 6000, 'queue_id': 7}}}}} on 2 hosts
2020-10-14 17:08:02,748 -  nornir.core -     INFO -        run() - Running task 'sap_cfg_xml_generation' with args {'svc_dict': {'svc': {'service': {'type': 'L2V', 'class': 'TST', 'descr': 'Ansible', 'svc_id': 500013}, 'attach_circuit_wan': [{'hostname': 'PE01LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'dot1q', 'mtu': '9212', 'vlan': '12', 'sap_descr': 'Automation', 'qos': 'BE', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE01LT2', 'port': '1/2/11', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'qinq', 'mtu': '9212', 'vlan': '100.*', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE02LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'null', 'mtu': '9212', 'vlan': '', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}]}}, 'attr_dict': {'pe': {'loopback': {'PE01LT2': {'id': 1}, 'PE02LT2': {'id': 2}}, 'qos': {'BE': {'fprdgrp': 'dc-vxlan-be', 'qos_id': 1, 'queue_id': 1}, 'AF': {'fprdgrp': 'dc-vxlan-af', 'qos_id': 6003, 'queue_id': 3}, 'EF': {'fprdgrp': 'dc-vxlan-ef', 'qos_id': 6001, 'queue_id': 6}, 'H1': {'fprdgrp': 'dc-vxlan-h1', 'qos_id': 6000, 'queue_id': 7}}}}} on 2 hosts
2020-10-14 17:08:02,787 -  nornir.core -     INFO -        run() - Running task 'full_cfg_xml_generation' with args {'svc_dict': {'svc': {'service': {'type': 'L2V', 'class': 'TST', 'descr': 'Ansible', 'svc_id': 500013}, 'attach_circuit_wan': [{'hostname': 'PE01LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'dot1q', 'mtu': '9212', 'vlan': '12', 'sap_descr': 'Automation', 'qos': 'BE', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE01LT2', 'port': '1/2/11', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'qinq', 'mtu': '9212', 'vlan': '100.*', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE02LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'null', 'mtu': '9212', 'vlan': '', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}]}}} on 2 hosts
2020-10-14 17:08:02,817 -  nornir.core -     INFO -        run() - Running task 'send_xml_payload' with args {} on 2 hosts
2020-10-14 17:08:04,246 - nornir.core.task -    ERROR -      start() - Host 'PE02LT2': task 'XML payload through Netconf' failed with traceback:
Traceback (most recent call last):
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir_scrapli/tasks/netconf_edit_config.py", line 27, in netconf_edit_config
    scrapli_conn = task.host.get_connection("scrapli_netconf", task.nornir.config)
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/inventory.py", line 440, in get_connection
    self.open_connection(
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/inventory.py", line 492, in open_connection
    conn_obj.open(
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir_scrapli/connection.py", line 157, in open
    connection.open()
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/driver/driver.py", line 55, in open
    login_bytes = self.transport.open_netconf()
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 35, in open_netconf
    login_bytes = self._open_netconf_pty()
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 59, in _open_netconf_pty
    login_bytes: bytes = self._authenticate()
  File "/home/fouine/.local/lib/python3.8/site-packages/scrapli/decorators.py", line 113, in decorate
    return self.multiprocessing_timeout(
  File "/home/fouine/.local/lib/python3.8/site-packages/scrapli/decorators.py", line 301, in multiprocessing_timeout
    result = future.get(timeout=self.timeout_duration)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 111, in _authenticate
    raise ScrapliAuthenticationFailed(msg)
scrapli.exceptions.ScrapliAuthenticationFailed: `password` seen multiple times during session establishment, likely failed authentication

2020-10-14 17:08:04,249 - nornir.core.task -    ERROR -      start() - Host 'PE01LT2': task 'XML payload through Netconf' failed with traceback:
Traceback (most recent call last):
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir_scrapli/tasks/netconf_edit_config.py", line 27, in netconf_edit_config
    scrapli_conn = task.host.get_connection("scrapli_netconf", task.nornir.config)
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/inventory.py", line 440, in get_connection
    self.open_connection(
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/inventory.py", line 492, in open_connection
    conn_obj.open(
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir_scrapli/connection.py", line 157, in open
    connection.open()
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/driver/driver.py", line 55, in open
    login_bytes = self.transport.open_netconf()
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 35, in open_netconf
    login_bytes = self._open_netconf_pty()
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 59, in _open_netconf_pty
    login_bytes: bytes = self._authenticate()
  File "/home/fouine/.local/lib/python3.8/site-packages/scrapli/decorators.py", line 113, in decorate
    return self.multiprocessing_timeout(
  File "/home/fouine/.local/lib/python3.8/site-packages/scrapli/decorators.py", line 301, in multiprocessing_timeout
    result = future.get(timeout=self.timeout_duration)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 111, in _authenticate
    raise ScrapliAuthenticationFailed(msg)
scrapli.exceptions.ScrapliAuthenticationFailed: `password` seen multiple times during session establishment, likely failed authentication

2020-10-14 17:09:12,616 -  nornir.core -     INFO -        run() - Running task 'port_cfg_xml_generation' with args {'svc_dict': {'svc': {'service': {'type': 'L2V', 'class': 'TST', 'descr': 'Ansible', 'svc_id': 500013}, 'attach_circuit_wan': [{'hostname': 'PE01LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'dot1q', 'mtu': '9212', 'vlan': '12', 'sap_descr': 'Automation', 'qos': 'BE', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE01LT2', 'port': '1/2/11', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'qinq', 'mtu': '9212', 'vlan': '100.*', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE02LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'null', 'mtu': '9212', 'vlan': '', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}]}}, 'attr_dict': {'pe': {'loopback': {'PE01LT2': {'id': 1}, 'PE02LT2': {'id': 2}}, 'qos': {'BE': {'fprdgrp': 'dc-vxlan-be', 'qos_id': 1, 'queue_id': 1}, 'AF': {'fprdgrp': 'dc-vxlan-af', 'qos_id': 6003, 'queue_id': 3}, 'EF': {'fprdgrp': 'dc-vxlan-ef', 'qos_id': 6001, 'queue_id': 6}, 'H1': {'fprdgrp': 'dc-vxlan-h1', 'qos_id': 6000, 'queue_id': 7}}}}} on 2 hosts
2020-10-14 17:09:12,628 -  nornir.core -     INFO -        run() - Running task 'svc_cfg_xml_generation' with args {'svc_dict': {'svc': {'service': {'type': 'L2V', 'class': 'TST', 'descr': 'Ansible', 'svc_id': 500013}, 'attach_circuit_wan': [{'hostname': 'PE01LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'dot1q', 'mtu': '9212', 'vlan': '12', 'sap_descr': 'Automation', 'qos': 'BE', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE01LT2', 'port': '1/2/11', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'qinq', 'mtu': '9212', 'vlan': '100.*', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE02LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'null', 'mtu': '9212', 'vlan': '', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}]}}, 'attr_dict': {'pe': {'loopback': {'PE01LT2': {'id': 1}, 'PE02LT2': {'id': 2}}, 'qos': {'BE': {'fprdgrp': 'dc-vxlan-be', 'qos_id': 1, 'queue_id': 1}, 'AF': {'fprdgrp': 'dc-vxlan-af', 'qos_id': 6003, 'queue_id': 3}, 'EF': {'fprdgrp': 'dc-vxlan-ef', 'qos_id': 6001, 'queue_id': 6}, 'H1': {'fprdgrp': 'dc-vxlan-h1', 'qos_id': 6000, 'queue_id': 7}}}}} on 2 hosts
2020-10-14 17:09:12,642 -  nornir.core -     INFO -        run() - Running task 'sap_cfg_xml_generation' with args {'svc_dict': {'svc': {'service': {'type': 'L2V', 'class': 'TST', 'descr': 'Ansible', 'svc_id': 500013}, 'attach_circuit_wan': [{'hostname': 'PE01LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'dot1q', 'mtu': '9212', 'vlan': '12', 'sap_descr': 'Automation', 'qos': 'BE', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE01LT2', 'port': '1/2/11', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'qinq', 'mtu': '9212', 'vlan': '100.*', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE02LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'null', 'mtu': '9212', 'vlan': '', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}]}}, 'attr_dict': {'pe': {'loopback': {'PE01LT2': {'id': 1}, 'PE02LT2': {'id': 2}}, 'qos': {'BE': {'fprdgrp': 'dc-vxlan-be', 'qos_id': 1, 'queue_id': 1}, 'AF': {'fprdgrp': 'dc-vxlan-af', 'qos_id': 6003, 'queue_id': 3}, 'EF': {'fprdgrp': 'dc-vxlan-ef', 'qos_id': 6001, 'queue_id': 6}, 'H1': {'fprdgrp': 'dc-vxlan-h1', 'qos_id': 6000, 'queue_id': 7}}}}} on 2 hosts
2020-10-14 17:09:12,662 -  nornir.core -     INFO -        run() - Running task 'full_cfg_xml_generation' with args {'svc_dict': {'svc': {'service': {'type': 'L2V', 'class': 'TST', 'descr': 'Ansible', 'svc_id': 500013}, 'attach_circuit_wan': [{'hostname': 'PE01LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'dot1q', 'mtu': '9212', 'vlan': '12', 'sap_descr': 'Automation', 'qos': 'BE', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE01LT2', 'port': '1/2/11', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'qinq', 'mtu': '9212', 'vlan': '100.*', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE02LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'null', 'mtu': '9212', 'vlan': '', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}]}}} on 2 hosts
2020-10-14 17:09:12,676 -  nornir.core -     INFO -        run() - Running task 'send_xml_payload' with args {} on 2 hosts
2020-10-14 17:09:13,780 - nornir.core.task -    ERROR -      start() - Host 'PE02LT2': task 'XML payload through Netconf' failed with traceback:
Traceback (most recent call last):
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir_scrapli/tasks/netconf_edit_config.py", line 27, in netconf_edit_config
    scrapli_conn = task.host.get_connection("scrapli_netconf", task.nornir.config)
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/inventory.py", line 440, in get_connection
    self.open_connection(
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/inventory.py", line 492, in open_connection
    conn_obj.open(
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir_scrapli/connection.py", line 157, in open
    connection.open()
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/driver/driver.py", line 55, in open
    login_bytes = self.transport.open_netconf()
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 35, in open_netconf
    login_bytes = self._open_netconf_pty()
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 59, in _open_netconf_pty
    login_bytes: bytes = self._authenticate()
  File "/home/fouine/.local/lib/python3.8/site-packages/scrapli/decorators.py", line 113, in decorate
    return self.multiprocessing_timeout(
  File "/home/fouine/.local/lib/python3.8/site-packages/scrapli/decorators.py", line 301, in multiprocessing_timeout
    result = future.get(timeout=self.timeout_duration)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 111, in _authenticate
    raise ScrapliAuthenticationFailed(msg)
scrapli.exceptions.ScrapliAuthenticationFailed: `password` seen multiple times during session establishment, likely failed authentication

2020-10-14 17:09:13,792 - nornir.core.task -    ERROR -      start() - Host 'PE01LT2': task 'XML payload through Netconf' failed with traceback:
Traceback (most recent call last):
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir_scrapli/tasks/netconf_edit_config.py", line 27, in netconf_edit_config
    scrapli_conn = task.host.get_connection("scrapli_netconf", task.nornir.config)
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/inventory.py", line 440, in get_connection
    self.open_connection(
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/inventory.py", line 492, in open_connection
    conn_obj.open(
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir_scrapli/connection.py", line 157, in open
    connection.open()
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/driver/driver.py", line 55, in open
    login_bytes = self.transport.open_netconf()
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 35, in open_netconf
    login_bytes = self._open_netconf_pty()
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 59, in _open_netconf_pty
    login_bytes: bytes = self._authenticate()
  File "/home/fouine/.local/lib/python3.8/site-packages/scrapli/decorators.py", line 113, in decorate
    return self.multiprocessing_timeout(
  File "/home/fouine/.local/lib/python3.8/site-packages/scrapli/decorators.py", line 301, in multiprocessing_timeout
    result = future.get(timeout=self.timeout_duration)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 111, in _authenticate
    raise ScrapliAuthenticationFailed(msg)
scrapli.exceptions.ScrapliAuthenticationFailed: `password` seen multiple times during session establishment, likely failed authentication

2020-10-14 17:11:26,693 -  nornir.core -     INFO -        run() - Running task 'port_cfg_xml_generation' with args {'svc_dict': {'svc': {'service': {'type': 'L2V', 'class': 'TST', 'descr': 'Ansible', 'svc_id': 500013}, 'attach_circuit_wan': [{'hostname': 'PE01LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'dot1q', 'mtu': '9212', 'vlan': '12', 'sap_descr': 'Automation', 'qos': 'BE', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE01LT2', 'port': '1/2/11', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'qinq', 'mtu': '9212', 'vlan': '100.*', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE02LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'null', 'mtu': '9212', 'vlan': '', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}]}}, 'attr_dict': {'pe': {'loopback': {'PE01LT2': {'id': 1}, 'PE02LT2': {'id': 2}}, 'qos': {'BE': {'fprdgrp': 'dc-vxlan-be', 'qos_id': 1, 'queue_id': 1}, 'AF': {'fprdgrp': 'dc-vxlan-af', 'qos_id': 6003, 'queue_id': 3}, 'EF': {'fprdgrp': 'dc-vxlan-ef', 'qos_id': 6001, 'queue_id': 6}, 'H1': {'fprdgrp': 'dc-vxlan-h1', 'qos_id': 6000, 'queue_id': 7}}}}} on 2 hosts
2020-10-14 17:11:26,704 -  nornir.core -     INFO -        run() - Running task 'svc_cfg_xml_generation' with args {'svc_dict': {'svc': {'service': {'type': 'L2V', 'class': 'TST', 'descr': 'Ansible', 'svc_id': 500013}, 'attach_circuit_wan': [{'hostname': 'PE01LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'dot1q', 'mtu': '9212', 'vlan': '12', 'sap_descr': 'Automation', 'qos': 'BE', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE01LT2', 'port': '1/2/11', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'qinq', 'mtu': '9212', 'vlan': '100.*', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE02LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'null', 'mtu': '9212', 'vlan': '', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}]}}, 'attr_dict': {'pe': {'loopback': {'PE01LT2': {'id': 1}, 'PE02LT2': {'id': 2}}, 'qos': {'BE': {'fprdgrp': 'dc-vxlan-be', 'qos_id': 1, 'queue_id': 1}, 'AF': {'fprdgrp': 'dc-vxlan-af', 'qos_id': 6003, 'queue_id': 3}, 'EF': {'fprdgrp': 'dc-vxlan-ef', 'qos_id': 6001, 'queue_id': 6}, 'H1': {'fprdgrp': 'dc-vxlan-h1', 'qos_id': 6000, 'queue_id': 7}}}}} on 2 hosts
2020-10-14 17:11:26,717 -  nornir.core -     INFO -        run() - Running task 'sap_cfg_xml_generation' with args {'svc_dict': {'svc': {'service': {'type': 'L2V', 'class': 'TST', 'descr': 'Ansible', 'svc_id': 500013}, 'attach_circuit_wan': [{'hostname': 'PE01LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'dot1q', 'mtu': '9212', 'vlan': '12', 'sap_descr': 'Automation', 'qos': 'BE', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE01LT2', 'port': '1/2/11', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'qinq', 'mtu': '9212', 'vlan': '100.*', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE02LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'null', 'mtu': '9212', 'vlan': '', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}]}}, 'attr_dict': {'pe': {'loopback': {'PE01LT2': {'id': 1}, 'PE02LT2': {'id': 2}}, 'qos': {'BE': {'fprdgrp': 'dc-vxlan-be', 'qos_id': 1, 'queue_id': 1}, 'AF': {'fprdgrp': 'dc-vxlan-af', 'qos_id': 6003, 'queue_id': 3}, 'EF': {'fprdgrp': 'dc-vxlan-ef', 'qos_id': 6001, 'queue_id': 6}, 'H1': {'fprdgrp': 'dc-vxlan-h1', 'qos_id': 6000, 'queue_id': 7}}}}} on 2 hosts
2020-10-14 17:11:26,735 -  nornir.core -     INFO -        run() - Running task 'full_cfg_xml_generation' with args {'svc_dict': {'svc': {'service': {'type': 'L2V', 'class': 'TST', 'descr': 'Ansible', 'svc_id': 500013}, 'attach_circuit_wan': [{'hostname': 'PE01LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'dot1q', 'mtu': '9212', 'vlan': '12', 'sap_descr': 'Automation', 'qos': 'BE', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE01LT2', 'port': '1/2/11', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'qinq', 'mtu': '9212', 'vlan': '100.*', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE02LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'null', 'mtu': '9212', 'vlan': '', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}]}}} on 2 hosts
2020-10-14 17:11:26,747 -  nornir.core -     INFO -        run() - Running task 'send_xml_payload' with args {} on 2 hosts
2020-10-14 17:11:26,751 - nornir.core.task -    ERROR -      start() - Host 'PE01LT2': task 'XML payload through Netconf' failed with traceback:
Traceback (most recent call last):
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir_scrapli/tasks/netconf_edit_config.py", line 27, in netconf_edit_config
    scrapli_conn = task.host.get_connection("scrapli_netconf", task.nornir.config)
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/inventory.py", line 440, in get_connection
    self.open_connection(
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/inventory.py", line 492, in open_connection
    conn_obj.open(
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir_scrapli/connection.py", line 156, in open
    connection = NetconfScrape(**parameters)
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/driver/driver.py", line 21, in __init__
    super().__init__(port=port, **kwargs)
  File "/home/fouine/.local/lib/python3.8/site-packages/scrapli/driver/driver.py", line 33, in __init__
    super().__init__(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'use_keys'

2020-10-14 17:11:26,751 - nornir.core.task -    ERROR -      start() - Host 'PE02LT2': task 'XML payload through Netconf' failed with traceback:
Traceback (most recent call last):
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir_scrapli/tasks/netconf_edit_config.py", line 27, in netconf_edit_config
    scrapli_conn = task.host.get_connection("scrapli_netconf", task.nornir.config)
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/inventory.py", line 440, in get_connection
    self.open_connection(
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/inventory.py", line 492, in open_connection
    conn_obj.open(
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir_scrapli/connection.py", line 156, in open
    connection = NetconfScrape(**parameters)
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/driver/driver.py", line 21, in __init__
    super().__init__(port=port, **kwargs)
  File "/home/fouine/.local/lib/python3.8/site-packages/scrapli/driver/driver.py", line 33, in __init__
    super().__init__(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'use_keys'

2020-10-14 17:11:46,927 -  nornir.core -     INFO -        run() - Running task 'port_cfg_xml_generation' with args {'svc_dict': {'svc': {'service': {'type': 'L2V', 'class': 'TST', 'descr': 'Ansible', 'svc_id': 500013}, 'attach_circuit_wan': [{'hostname': 'PE01LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'dot1q', 'mtu': '9212', 'vlan': '12', 'sap_descr': 'Automation', 'qos': 'BE', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE01LT2', 'port': '1/2/11', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'qinq', 'mtu': '9212', 'vlan': '100.*', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE02LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'null', 'mtu': '9212', 'vlan': '', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}]}}, 'attr_dict': {'pe': {'loopback': {'PE01LT2': {'id': 1}, 'PE02LT2': {'id': 2}}, 'qos': {'BE': {'fprdgrp': 'dc-vxlan-be', 'qos_id': 1, 'queue_id': 1}, 'AF': {'fprdgrp': 'dc-vxlan-af', 'qos_id': 6003, 'queue_id': 3}, 'EF': {'fprdgrp': 'dc-vxlan-ef', 'qos_id': 6001, 'queue_id': 6}, 'H1': {'fprdgrp': 'dc-vxlan-h1', 'qos_id': 6000, 'queue_id': 7}}}}} on 2 hosts
2020-10-14 17:11:46,939 -  nornir.core -     INFO -        run() - Running task 'svc_cfg_xml_generation' with args {'svc_dict': {'svc': {'service': {'type': 'L2V', 'class': 'TST', 'descr': 'Ansible', 'svc_id': 500013}, 'attach_circuit_wan': [{'hostname': 'PE01LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'dot1q', 'mtu': '9212', 'vlan': '12', 'sap_descr': 'Automation', 'qos': 'BE', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE01LT2', 'port': '1/2/11', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'qinq', 'mtu': '9212', 'vlan': '100.*', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE02LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'null', 'mtu': '9212', 'vlan': '', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}]}}, 'attr_dict': {'pe': {'loopback': {'PE01LT2': {'id': 1}, 'PE02LT2': {'id': 2}}, 'qos': {'BE': {'fprdgrp': 'dc-vxlan-be', 'qos_id': 1, 'queue_id': 1}, 'AF': {'fprdgrp': 'dc-vxlan-af', 'qos_id': 6003, 'queue_id': 3}, 'EF': {'fprdgrp': 'dc-vxlan-ef', 'qos_id': 6001, 'queue_id': 6}, 'H1': {'fprdgrp': 'dc-vxlan-h1', 'qos_id': 6000, 'queue_id': 7}}}}} on 2 hosts
2020-10-14 17:11:46,951 -  nornir.core -     INFO -        run() - Running task 'sap_cfg_xml_generation' with args {'svc_dict': {'svc': {'service': {'type': 'L2V', 'class': 'TST', 'descr': 'Ansible', 'svc_id': 500013}, 'attach_circuit_wan': [{'hostname': 'PE01LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'dot1q', 'mtu': '9212', 'vlan': '12', 'sap_descr': 'Automation', 'qos': 'BE', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE01LT2', 'port': '1/2/11', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'qinq', 'mtu': '9212', 'vlan': '100.*', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE02LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'null', 'mtu': '9212', 'vlan': '', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}]}}, 'attr_dict': {'pe': {'loopback': {'PE01LT2': {'id': 1}, 'PE02LT2': {'id': 2}}, 'qos': {'BE': {'fprdgrp': 'dc-vxlan-be', 'qos_id': 1, 'queue_id': 1}, 'AF': {'fprdgrp': 'dc-vxlan-af', 'qos_id': 6003, 'queue_id': 3}, 'EF': {'fprdgrp': 'dc-vxlan-ef', 'qos_id': 6001, 'queue_id': 6}, 'H1': {'fprdgrp': 'dc-vxlan-h1', 'qos_id': 6000, 'queue_id': 7}}}}} on 2 hosts
2020-10-14 17:11:46,969 -  nornir.core -     INFO -        run() - Running task 'full_cfg_xml_generation' with args {'svc_dict': {'svc': {'service': {'type': 'L2V', 'class': 'TST', 'descr': 'Ansible', 'svc_id': 500013}, 'attach_circuit_wan': [{'hostname': 'PE01LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'dot1q', 'mtu': '9212', 'vlan': '12', 'sap_descr': 'Automation', 'qos': 'BE', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE01LT2', 'port': '1/2/11', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'qinq', 'mtu': '9212', 'vlan': '100.*', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE02LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'null', 'mtu': '9212', 'vlan': '', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}]}}} on 2 hosts
2020-10-14 17:11:46,982 -  nornir.core -     INFO -        run() - Running task 'send_xml_payload' with args {} on 2 hosts
2020-10-14 17:11:47,981 - nornir.core.task -    ERROR -      start() - Host 'PE02LT2': task 'XML payload through Netconf' failed with traceback:
Traceback (most recent call last):
  File "/home/fouine/.local/lib/python3.8/site-packages/scrapli/transport/ptyprocess.py", line 376, in read
    s = self.fileobj.read1(size)
OSError: [Errno 5] Input/output error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 85, in _authenticate
    new_output = self.session.read()
  File "/home/fouine/.local/lib/python3.8/site-packages/scrapli/transport/ptyprocess.py", line 381, in read
    raise EOFError("End Of File (EOF). Exception style platform.")
EOFError: End Of File (EOF). Exception style platform.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir_scrapli/tasks/netconf_edit_config.py", line 27, in netconf_edit_config
    scrapli_conn = task.host.get_connection("scrapli_netconf", task.nornir.config)
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/inventory.py", line 440, in get_connection
    self.open_connection(
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/inventory.py", line 492, in open_connection
    conn_obj.open(
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir_scrapli/connection.py", line 157, in open
    connection.open()
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/driver/driver.py", line 55, in open
    login_bytes = self.transport.open_netconf()
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 35, in open_netconf
    login_bytes = self._open_netconf_pty()
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 59, in _open_netconf_pty
    login_bytes: bytes = self._authenticate()
  File "/home/fouine/.local/lib/python3.8/site-packages/scrapli/decorators.py", line 113, in decorate
    return self.multiprocessing_timeout(
  File "/home/fouine/.local/lib/python3.8/site-packages/scrapli/decorators.py", line 301, in multiprocessing_timeout
    result = future.get(timeout=self.timeout_duration)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 97, in _authenticate
    raise ScrapliAuthenticationFailed(msg) from exc
scrapli.exceptions.ScrapliAuthenticationFailed: Failed to open connection to host PE02LT2. Do you need to disable `auth_strict_key`?

2020-10-14 17:11:48,017 - nornir.core.task -    ERROR -      start() - Host 'PE01LT2': task 'XML payload through Netconf' failed with traceback:
Traceback (most recent call last):
  File "/home/fouine/.local/lib/python3.8/site-packages/scrapli/transport/ptyprocess.py", line 376, in read
    s = self.fileobj.read1(size)
OSError: [Errno 5] Input/output error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 85, in _authenticate
    new_output = self.session.read()
  File "/home/fouine/.local/lib/python3.8/site-packages/scrapli/transport/ptyprocess.py", line 381, in read
    raise EOFError("End Of File (EOF). Exception style platform.")
EOFError: End Of File (EOF). Exception style platform.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir_scrapli/tasks/netconf_edit_config.py", line 27, in netconf_edit_config
    scrapli_conn = task.host.get_connection("scrapli_netconf", task.nornir.config)
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/inventory.py", line 440, in get_connection
    self.open_connection(
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/inventory.py", line 492, in open_connection
    conn_obj.open(
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir_scrapli/connection.py", line 157, in open
    connection.open()
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/driver/driver.py", line 55, in open
    login_bytes = self.transport.open_netconf()
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 35, in open_netconf
    login_bytes = self._open_netconf_pty()
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 59, in _open_netconf_pty
    login_bytes: bytes = self._authenticate()
  File "/home/fouine/.local/lib/python3.8/site-packages/scrapli/decorators.py", line 113, in decorate
    return self.multiprocessing_timeout(
  File "/home/fouine/.local/lib/python3.8/site-packages/scrapli/decorators.py", line 301, in multiprocessing_timeout
    result = future.get(timeout=self.timeout_duration)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 97, in _authenticate
    raise ScrapliAuthenticationFailed(msg) from exc
scrapli.exceptions.ScrapliAuthenticationFailed: Failed to open connection to host PE01LT2. Do you need to disable `auth_strict_key`?

2020-10-14 17:15:28,200 -  nornir.core -     INFO -        run() - Running task 'port_cfg_xml_generation' with args {'svc_dict': {'svc': {'service': {'type': 'L2V', 'class': 'TST', 'descr': 'Ansible', 'svc_id': 500013}, 'attach_circuit_wan': [{'hostname': 'PE01LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'dot1q', 'mtu': '9212', 'vlan': '12', 'sap_descr': 'Automation', 'qos': 'BE', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE01LT2', 'port': '1/2/11', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'qinq', 'mtu': '9212', 'vlan': '100.*', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE02LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'null', 'mtu': '9212', 'vlan': '', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}]}}, 'attr_dict': {'pe': {'loopback': {'PE01LT2': {'id': 1}, 'PE02LT2': {'id': 2}}, 'qos': {'BE': {'fprdgrp': 'dc-vxlan-be', 'qos_id': 1, 'queue_id': 1}, 'AF': {'fprdgrp': 'dc-vxlan-af', 'qos_id': 6003, 'queue_id': 3}, 'EF': {'fprdgrp': 'dc-vxlan-ef', 'qos_id': 6001, 'queue_id': 6}, 'H1': {'fprdgrp': 'dc-vxlan-h1', 'qos_id': 6000, 'queue_id': 7}}}}} on 2 hosts
2020-10-14 17:15:28,210 -  nornir.core -     INFO -        run() - Running task 'svc_cfg_xml_generation' with args {'svc_dict': {'svc': {'service': {'type': 'L2V', 'class': 'TST', 'descr': 'Ansible', 'svc_id': 500013}, 'attach_circuit_wan': [{'hostname': 'PE01LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'dot1q', 'mtu': '9212', 'vlan': '12', 'sap_descr': 'Automation', 'qos': 'BE', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE01LT2', 'port': '1/2/11', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'qinq', 'mtu': '9212', 'vlan': '100.*', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE02LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'null', 'mtu': '9212', 'vlan': '', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}]}}, 'attr_dict': {'pe': {'loopback': {'PE01LT2': {'id': 1}, 'PE02LT2': {'id': 2}}, 'qos': {'BE': {'fprdgrp': 'dc-vxlan-be', 'qos_id': 1, 'queue_id': 1}, 'AF': {'fprdgrp': 'dc-vxlan-af', 'qos_id': 6003, 'queue_id': 3}, 'EF': {'fprdgrp': 'dc-vxlan-ef', 'qos_id': 6001, 'queue_id': 6}, 'H1': {'fprdgrp': 'dc-vxlan-h1', 'qos_id': 6000, 'queue_id': 7}}}}} on 2 hosts
2020-10-14 17:15:28,221 -  nornir.core -     INFO -        run() - Running task 'sap_cfg_xml_generation' with args {'svc_dict': {'svc': {'service': {'type': 'L2V', 'class': 'TST', 'descr': 'Ansible', 'svc_id': 500013}, 'attach_circuit_wan': [{'hostname': 'PE01LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'dot1q', 'mtu': '9212', 'vlan': '12', 'sap_descr': 'Automation', 'qos': 'BE', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE01LT2', 'port': '1/2/11', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'qinq', 'mtu': '9212', 'vlan': '100.*', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE02LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'null', 'mtu': '9212', 'vlan': '', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}]}}, 'attr_dict': {'pe': {'loopback': {'PE01LT2': {'id': 1}, 'PE02LT2': {'id': 2}}, 'qos': {'BE': {'fprdgrp': 'dc-vxlan-be', 'qos_id': 1, 'queue_id': 1}, 'AF': {'fprdgrp': 'dc-vxlan-af', 'qos_id': 6003, 'queue_id': 3}, 'EF': {'fprdgrp': 'dc-vxlan-ef', 'qos_id': 6001, 'queue_id': 6}, 'H1': {'fprdgrp': 'dc-vxlan-h1', 'qos_id': 6000, 'queue_id': 7}}}}} on 2 hosts
2020-10-14 17:15:28,237 -  nornir.core -     INFO -        run() - Running task 'full_cfg_xml_generation' with args {'svc_dict': {'svc': {'service': {'type': 'L2V', 'class': 'TST', 'descr': 'Ansible', 'svc_id': 500013}, 'attach_circuit_wan': [{'hostname': 'PE01LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'dot1q', 'mtu': '9212', 'vlan': '12', 'sap_descr': 'Automation', 'qos': 'BE', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE01LT2', 'port': '1/2/11', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'qinq', 'mtu': '9212', 'vlan': '100.*', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE02LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'null', 'mtu': '9212', 'vlan': '', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}]}}} on 2 hosts
2020-10-14 17:15:28,248 -  nornir.core -     INFO -        run() - Running task 'send_xml_payload' with args {} on 2 hosts
2020-10-14 17:15:29,231 - nornir.core.task -    ERROR -      start() - Host 'PE01LT2': task 'XML payload through Netconf' failed with traceback:
Traceback (most recent call last):
  File "/home/fouine/.local/lib/python3.8/site-packages/scrapli/transport/ptyprocess.py", line 376, in read
    s = self.fileobj.read1(size)
OSError: [Errno 5] Input/output error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 85, in _authenticate
    new_output = self.session.read()
  File "/home/fouine/.local/lib/python3.8/site-packages/scrapli/transport/ptyprocess.py", line 381, in read
    raise EOFError("End Of File (EOF). Exception style platform.")
EOFError: End Of File (EOF). Exception style platform.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir_scrapli/tasks/netconf_edit_config.py", line 27, in netconf_edit_config
    scrapli_conn = task.host.get_connection("scrapli_netconf", task.nornir.config)
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/inventory.py", line 440, in get_connection
    self.open_connection(
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/inventory.py", line 492, in open_connection
    conn_obj.open(
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir_scrapli/connection.py", line 157, in open
    connection.open()
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/driver/driver.py", line 55, in open
    login_bytes = self.transport.open_netconf()
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 35, in open_netconf
    login_bytes = self._open_netconf_pty()
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 59, in _open_netconf_pty
    login_bytes: bytes = self._authenticate()
  File "/home/fouine/.local/lib/python3.8/site-packages/scrapli/decorators.py", line 113, in decorate
    return self.multiprocessing_timeout(
  File "/home/fouine/.local/lib/python3.8/site-packages/scrapli/decorators.py", line 301, in multiprocessing_timeout
    result = future.get(timeout=self.timeout_duration)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 97, in _authenticate
    raise ScrapliAuthenticationFailed(msg) from exc
scrapli.exceptions.ScrapliAuthenticationFailed: Failed to open connection to host PE01LT2. Do you need to disable `auth_strict_key`?

2020-10-14 17:15:29,232 - nornir.core.task -    ERROR -      start() - Host 'PE02LT2': task 'XML payload through Netconf' failed with traceback:
Traceback (most recent call last):
  File "/home/fouine/.local/lib/python3.8/site-packages/scrapli/transport/ptyprocess.py", line 376, in read
    s = self.fileobj.read1(size)
OSError: [Errno 5] Input/output error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 85, in _authenticate
    new_output = self.session.read()
  File "/home/fouine/.local/lib/python3.8/site-packages/scrapli/transport/ptyprocess.py", line 381, in read
    raise EOFError("End Of File (EOF). Exception style platform.")
EOFError: End Of File (EOF). Exception style platform.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir_scrapli/tasks/netconf_edit_config.py", line 27, in netconf_edit_config
    scrapli_conn = task.host.get_connection("scrapli_netconf", task.nornir.config)
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/inventory.py", line 440, in get_connection
    self.open_connection(
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/inventory.py", line 492, in open_connection
    conn_obj.open(
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir_scrapli/connection.py", line 157, in open
    connection.open()
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/driver/driver.py", line 55, in open
    login_bytes = self.transport.open_netconf()
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 35, in open_netconf
    login_bytes = self._open_netconf_pty()
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 59, in _open_netconf_pty
    login_bytes: bytes = self._authenticate()
  File "/home/fouine/.local/lib/python3.8/site-packages/scrapli/decorators.py", line 113, in decorate
    return self.multiprocessing_timeout(
  File "/home/fouine/.local/lib/python3.8/site-packages/scrapli/decorators.py", line 301, in multiprocessing_timeout
    result = future.get(timeout=self.timeout_duration)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 97, in _authenticate
    raise ScrapliAuthenticationFailed(msg) from exc
scrapli.exceptions.ScrapliAuthenticationFailed: Failed to open connection to host PE02LT2. Do you need to disable `auth_strict_key`?

2020-10-14 17:23:10,667 -  nornir.core -     INFO -        run() - Running task 'port_cfg_xml_generation' with args {'svc_dict': {'svc': {'service': {'type': 'L2V', 'class': 'TST', 'descr': 'Ansible', 'svc_id': 500013}, 'attach_circuit_wan': [{'hostname': 'PE01LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'dot1q', 'mtu': '9212', 'vlan': '12', 'sap_descr': 'Automation', 'qos': 'BE', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE01LT2', 'port': '1/2/11', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'qinq', 'mtu': '9212', 'vlan': '100.*', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE02LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'null', 'mtu': '9212', 'vlan': '', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}]}}, 'attr_dict': {'pe': {'loopback': {'PE01LT2': {'id': 1}, 'PE02LT2': {'id': 2}}, 'qos': {'BE': {'fprdgrp': 'dc-vxlan-be', 'qos_id': 1, 'queue_id': 1}, 'AF': {'fprdgrp': 'dc-vxlan-af', 'qos_id': 6003, 'queue_id': 3}, 'EF': {'fprdgrp': 'dc-vxlan-ef', 'qos_id': 6001, 'queue_id': 6}, 'H1': {'fprdgrp': 'dc-vxlan-h1', 'qos_id': 6000, 'queue_id': 7}}}}} on 2 hosts
2020-10-14 17:23:10,677 -  nornir.core -     INFO -        run() - Running task 'svc_cfg_xml_generation' with args {'svc_dict': {'svc': {'service': {'type': 'L2V', 'class': 'TST', 'descr': 'Ansible', 'svc_id': 500013}, 'attach_circuit_wan': [{'hostname': 'PE01LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'dot1q', 'mtu': '9212', 'vlan': '12', 'sap_descr': 'Automation', 'qos': 'BE', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE01LT2', 'port': '1/2/11', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'qinq', 'mtu': '9212', 'vlan': '100.*', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE02LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'null', 'mtu': '9212', 'vlan': '', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}]}}, 'attr_dict': {'pe': {'loopback': {'PE01LT2': {'id': 1}, 'PE02LT2': {'id': 2}}, 'qos': {'BE': {'fprdgrp': 'dc-vxlan-be', 'qos_id': 1, 'queue_id': 1}, 'AF': {'fprdgrp': 'dc-vxlan-af', 'qos_id': 6003, 'queue_id': 3}, 'EF': {'fprdgrp': 'dc-vxlan-ef', 'qos_id': 6001, 'queue_id': 6}, 'H1': {'fprdgrp': 'dc-vxlan-h1', 'qos_id': 6000, 'queue_id': 7}}}}} on 2 hosts
2020-10-14 17:23:10,687 -  nornir.core -     INFO -        run() - Running task 'sap_cfg_xml_generation' with args {'svc_dict': {'svc': {'service': {'type': 'L2V', 'class': 'TST', 'descr': 'Ansible', 'svc_id': 500013}, 'attach_circuit_wan': [{'hostname': 'PE01LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'dot1q', 'mtu': '9212', 'vlan': '12', 'sap_descr': 'Automation', 'qos': 'BE', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE01LT2', 'port': '1/2/11', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'qinq', 'mtu': '9212', 'vlan': '100.*', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE02LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'null', 'mtu': '9212', 'vlan': '', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}]}}, 'attr_dict': {'pe': {'loopback': {'PE01LT2': {'id': 1}, 'PE02LT2': {'id': 2}}, 'qos': {'BE': {'fprdgrp': 'dc-vxlan-be', 'qos_id': 1, 'queue_id': 1}, 'AF': {'fprdgrp': 'dc-vxlan-af', 'qos_id': 6003, 'queue_id': 3}, 'EF': {'fprdgrp': 'dc-vxlan-ef', 'qos_id': 6001, 'queue_id': 6}, 'H1': {'fprdgrp': 'dc-vxlan-h1', 'qos_id': 6000, 'queue_id': 7}}}}} on 2 hosts
2020-10-14 17:23:10,704 -  nornir.core -     INFO -        run() - Running task 'full_cfg_xml_generation' with args {'svc_dict': {'svc': {'service': {'type': 'L2V', 'class': 'TST', 'descr': 'Ansible', 'svc_id': 500013}, 'attach_circuit_wan': [{'hostname': 'PE01LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'dot1q', 'mtu': '9212', 'vlan': '12', 'sap_descr': 'Automation', 'qos': 'BE', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE01LT2', 'port': '1/2/11', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'qinq', 'mtu': '9212', 'vlan': '100.*', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE02LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'null', 'mtu': '9212', 'vlan': '', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}]}}} on 2 hosts
2020-10-14 17:23:10,715 -  nornir.core -     INFO -        run() - Running task 'send_xml_payload' with args {} on 2 hosts
2020-10-14 17:23:11,470 - nornir.core.task -    ERROR -      start() - Host 'PE02LT2': task 'XML payload through Netconf' failed with traceback:
Traceback (most recent call last):
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir_scrapli/tasks/netconf_edit_config.py", line 27, in netconf_edit_config
    scrapli_conn = task.host.get_connection("scrapli_netconf", task.nornir.config)
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/inventory.py", line 440, in get_connection
    self.open_connection(
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/inventory.py", line 492, in open_connection
    conn_obj.open(
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir_scrapli/connection.py", line 157, in open
    connection.open()
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/driver/driver.py", line 55, in open
    login_bytes = self.transport.open_netconf()
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 35, in open_netconf
    login_bytes = self._open_netconf_pty()
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 59, in _open_netconf_pty
    login_bytes: bytes = self._authenticate()
  File "/home/fouine/.local/lib/python3.8/site-packages/scrapli/decorators.py", line 113, in decorate
    return self.multiprocessing_timeout(
  File "/home/fouine/.local/lib/python3.8/site-packages/scrapli/decorators.py", line 301, in multiprocessing_timeout
    result = future.get(timeout=self.timeout_duration)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 111, in _authenticate
    raise ScrapliAuthenticationFailed(msg)
scrapli.exceptions.ScrapliAuthenticationFailed: `password` seen multiple times during session establishment, likely failed authentication

2020-10-14 17:23:11,481 - nornir.core.task -    ERROR -      start() - Host 'PE01LT2': task 'XML payload through Netconf' failed with traceback:
Traceback (most recent call last):
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir_scrapli/tasks/netconf_edit_config.py", line 27, in netconf_edit_config
    scrapli_conn = task.host.get_connection("scrapli_netconf", task.nornir.config)
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/inventory.py", line 440, in get_connection
    self.open_connection(
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/inventory.py", line 492, in open_connection
    conn_obj.open(
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir_scrapli/connection.py", line 157, in open
    connection.open()
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/driver/driver.py", line 55, in open
    login_bytes = self.transport.open_netconf()
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 35, in open_netconf
    login_bytes = self._open_netconf_pty()
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 59, in _open_netconf_pty
    login_bytes: bytes = self._authenticate()
  File "/home/fouine/.local/lib/python3.8/site-packages/scrapli/decorators.py", line 113, in decorate
    return self.multiprocessing_timeout(
  File "/home/fouine/.local/lib/python3.8/site-packages/scrapli/decorators.py", line 301, in multiprocessing_timeout
    result = future.get(timeout=self.timeout_duration)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 111, in _authenticate
    raise ScrapliAuthenticationFailed(msg)
scrapli.exceptions.ScrapliAuthenticationFailed: `password` seen multiple times during session establishment, likely failed authentication

2020-10-14 17:23:31,517 -  nornir.core -     INFO -        run() - Running task 'port_cfg_xml_generation' with args {'svc_dict': {'svc': {'service': {'type': 'L2V', 'class': 'TST', 'descr': 'Ansible', 'svc_id': 500013}, 'attach_circuit_wan': [{'hostname': 'PE01LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'dot1q', 'mtu': '9212', 'vlan': '12', 'sap_descr': 'Automation', 'qos': 'BE', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE01LT2', 'port': '1/2/11', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'qinq', 'mtu': '9212', 'vlan': '100.*', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE02LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'null', 'mtu': '9212', 'vlan': '', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}]}}, 'attr_dict': {'pe': {'loopback': {'PE01LT2': {'id': 1}, 'PE02LT2': {'id': 2}}, 'qos': {'BE': {'fprdgrp': 'dc-vxlan-be', 'qos_id': 1, 'queue_id': 1}, 'AF': {'fprdgrp': 'dc-vxlan-af', 'qos_id': 6003, 'queue_id': 3}, 'EF': {'fprdgrp': 'dc-vxlan-ef', 'qos_id': 6001, 'queue_id': 6}, 'H1': {'fprdgrp': 'dc-vxlan-h1', 'qos_id': 6000, 'queue_id': 7}}}}} on 2 hosts
2020-10-14 17:23:31,527 -  nornir.core -     INFO -        run() - Running task 'svc_cfg_xml_generation' with args {'svc_dict': {'svc': {'service': {'type': 'L2V', 'class': 'TST', 'descr': 'Ansible', 'svc_id': 500013}, 'attach_circuit_wan': [{'hostname': 'PE01LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'dot1q', 'mtu': '9212', 'vlan': '12', 'sap_descr': 'Automation', 'qos': 'BE', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE01LT2', 'port': '1/2/11', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'qinq', 'mtu': '9212', 'vlan': '100.*', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE02LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'null', 'mtu': '9212', 'vlan': '', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}]}}, 'attr_dict': {'pe': {'loopback': {'PE01LT2': {'id': 1}, 'PE02LT2': {'id': 2}}, 'qos': {'BE': {'fprdgrp': 'dc-vxlan-be', 'qos_id': 1, 'queue_id': 1}, 'AF': {'fprdgrp': 'dc-vxlan-af', 'qos_id': 6003, 'queue_id': 3}, 'EF': {'fprdgrp': 'dc-vxlan-ef', 'qos_id': 6001, 'queue_id': 6}, 'H1': {'fprdgrp': 'dc-vxlan-h1', 'qos_id': 6000, 'queue_id': 7}}}}} on 2 hosts
2020-10-14 17:23:31,538 -  nornir.core -     INFO -        run() - Running task 'sap_cfg_xml_generation' with args {'svc_dict': {'svc': {'service': {'type': 'L2V', 'class': 'TST', 'descr': 'Ansible', 'svc_id': 500013}, 'attach_circuit_wan': [{'hostname': 'PE01LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'dot1q', 'mtu': '9212', 'vlan': '12', 'sap_descr': 'Automation', 'qos': 'BE', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE01LT2', 'port': '1/2/11', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'qinq', 'mtu': '9212', 'vlan': '100.*', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE02LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'null', 'mtu': '9212', 'vlan': '', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}]}}, 'attr_dict': {'pe': {'loopback': {'PE01LT2': {'id': 1}, 'PE02LT2': {'id': 2}}, 'qos': {'BE': {'fprdgrp': 'dc-vxlan-be', 'qos_id': 1, 'queue_id': 1}, 'AF': {'fprdgrp': 'dc-vxlan-af', 'qos_id': 6003, 'queue_id': 3}, 'EF': {'fprdgrp': 'dc-vxlan-ef', 'qos_id': 6001, 'queue_id': 6}, 'H1': {'fprdgrp': 'dc-vxlan-h1', 'qos_id': 6000, 'queue_id': 7}}}}} on 2 hosts
2020-10-14 17:23:31,554 -  nornir.core -     INFO -        run() - Running task 'full_cfg_xml_generation' with args {'svc_dict': {'svc': {'service': {'type': 'L2V', 'class': 'TST', 'descr': 'Ansible', 'svc_id': 500013}, 'attach_circuit_wan': [{'hostname': 'PE01LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'dot1q', 'mtu': '9212', 'vlan': '12', 'sap_descr': 'Automation', 'qos': 'BE', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE01LT2', 'port': '1/2/11', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'qinq', 'mtu': '9212', 'vlan': '100.*', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE02LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'null', 'mtu': '9212', 'vlan': '', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}]}}} on 2 hosts
2020-10-14 17:23:31,566 -  nornir.core -     INFO -        run() - Running task 'send_xml_payload' with args {} on 2 hosts
2020-10-14 17:23:32,734 - nornir.core.task -    ERROR -      start() - Host 'PE02LT2': task 'XML payload through Netconf' failed with traceback:
Traceback (most recent call last):
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir_scrapli/tasks/netconf_edit_config.py", line 27, in netconf_edit_config
    scrapli_conn = task.host.get_connection("scrapli_netconf", task.nornir.config)
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/inventory.py", line 440, in get_connection
    self.open_connection(
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/inventory.py", line 492, in open_connection
    conn_obj.open(
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir_scrapli/connection.py", line 157, in open
    connection.open()
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/driver/driver.py", line 55, in open
    login_bytes = self.transport.open_netconf()
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 35, in open_netconf
    login_bytes = self._open_netconf_pty()
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 59, in _open_netconf_pty
    login_bytes: bytes = self._authenticate()
  File "/home/fouine/.local/lib/python3.8/site-packages/scrapli/decorators.py", line 113, in decorate
    return self.multiprocessing_timeout(
  File "/home/fouine/.local/lib/python3.8/site-packages/scrapli/decorators.py", line 301, in multiprocessing_timeout
    result = future.get(timeout=self.timeout_duration)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 111, in _authenticate
    raise ScrapliAuthenticationFailed(msg)
scrapli.exceptions.ScrapliAuthenticationFailed: `password` seen multiple times during session establishment, likely failed authentication

2020-10-14 17:23:32,770 - nornir.core.task -    ERROR -      start() - Host 'PE01LT2': task 'XML payload through Netconf' failed with traceback:
Traceback (most recent call last):
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir_scrapli/tasks/netconf_edit_config.py", line 27, in netconf_edit_config
    scrapli_conn = task.host.get_connection("scrapli_netconf", task.nornir.config)
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/inventory.py", line 440, in get_connection
    self.open_connection(
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir/core/inventory.py", line 492, in open_connection
    conn_obj.open(
  File "/home/fouine/.local/lib/python3.8/site-packages/nornir_scrapli/connection.py", line 157, in open
    connection.open()
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/driver/driver.py", line 55, in open
    login_bytes = self.transport.open_netconf()
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 35, in open_netconf
    login_bytes = self._open_netconf_pty()
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 59, in _open_netconf_pty
    login_bytes: bytes = self._authenticate()
  File "/home/fouine/.local/lib/python3.8/site-packages/scrapli/decorators.py", line 113, in decorate
    return self.multiprocessing_timeout(
  File "/home/fouine/.local/lib/python3.8/site-packages/scrapli/decorators.py", line 301, in multiprocessing_timeout
    result = future.get(timeout=self.timeout_duration)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/fouine/src/scrapli-netconf/scrapli_netconf/transport/systemssh.py", line 111, in _authenticate
    raise ScrapliAuthenticationFailed(msg)
scrapli.exceptions.ScrapliAuthenticationFailed: `password` seen multiple times during session establishment, likely failed authentication

2020-10-14 17:23:51,529 -  nornir.core -     INFO -        run() - Running task 'port_cfg_xml_generation' with args {'svc_dict': {'svc': {'service': {'type': 'L2V', 'class': 'TST', 'descr': 'Ansible', 'svc_id': 500013}, 'attach_circuit_wan': [{'hostname': 'PE01LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'dot1q', 'mtu': '9212', 'vlan': '12', 'sap_descr': 'Automation', 'qos': 'BE', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE01LT2', 'port': '1/2/11', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'qinq', 'mtu': '9212', 'vlan': '100.*', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE02LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'null', 'mtu': '9212', 'vlan': '', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}]}}, 'attr_dict': {'pe': {'loopback': {'PE01LT2': {'id': 1}, 'PE02LT2': {'id': 2}}, 'qos': {'BE': {'fprdgrp': 'dc-vxlan-be', 'qos_id': 1, 'queue_id': 1}, 'AF': {'fprdgrp': 'dc-vxlan-af', 'qos_id': 6003, 'queue_id': 3}, 'EF': {'fprdgrp': 'dc-vxlan-ef', 'qos_id': 6001, 'queue_id': 6}, 'H1': {'fprdgrp': 'dc-vxlan-h1', 'qos_id': 6000, 'queue_id': 7}}}}} on 2 hosts
2020-10-14 17:23:51,540 -  nornir.core -     INFO -        run() - Running task 'svc_cfg_xml_generation' with args {'svc_dict': {'svc': {'service': {'type': 'L2V', 'class': 'TST', 'descr': 'Ansible', 'svc_id': 500013}, 'attach_circuit_wan': [{'hostname': 'PE01LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'dot1q', 'mtu': '9212', 'vlan': '12', 'sap_descr': 'Automation', 'qos': 'BE', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE01LT2', 'port': '1/2/11', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'qinq', 'mtu': '9212', 'vlan': '100.*', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE02LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'null', 'mtu': '9212', 'vlan': '', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}]}}, 'attr_dict': {'pe': {'loopback': {'PE01LT2': {'id': 1}, 'PE02LT2': {'id': 2}}, 'qos': {'BE': {'fprdgrp': 'dc-vxlan-be', 'qos_id': 1, 'queue_id': 1}, 'AF': {'fprdgrp': 'dc-vxlan-af', 'qos_id': 6003, 'queue_id': 3}, 'EF': {'fprdgrp': 'dc-vxlan-ef', 'qos_id': 6001, 'queue_id': 6}, 'H1': {'fprdgrp': 'dc-vxlan-h1', 'qos_id': 6000, 'queue_id': 7}}}}} on 2 hosts
2020-10-14 17:23:51,551 -  nornir.core -     INFO -        run() - Running task 'sap_cfg_xml_generation' with args {'svc_dict': {'svc': {'service': {'type': 'L2V', 'class': 'TST', 'descr': 'Ansible', 'svc_id': 500013}, 'attach_circuit_wan': [{'hostname': 'PE01LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'dot1q', 'mtu': '9212', 'vlan': '12', 'sap_descr': 'Automation', 'qos': 'BE', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE01LT2', 'port': '1/2/11', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'qinq', 'mtu': '9212', 'vlan': '100.*', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE02LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'null', 'mtu': '9212', 'vlan': '', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}]}}, 'attr_dict': {'pe': {'loopback': {'PE01LT2': {'id': 1}, 'PE02LT2': {'id': 2}}, 'qos': {'BE': {'fprdgrp': 'dc-vxlan-be', 'qos_id': 1, 'queue_id': 1}, 'AF': {'fprdgrp': 'dc-vxlan-af', 'qos_id': 6003, 'queue_id': 3}, 'EF': {'fprdgrp': 'dc-vxlan-ef', 'qos_id': 6001, 'queue_id': 6}, 'H1': {'fprdgrp': 'dc-vxlan-h1', 'qos_id': 6000, 'queue_id': 7}}}}} on 2 hosts
2020-10-14 17:23:51,567 -  nornir.core -     INFO -        run() - Running task 'full_cfg_xml_generation' with args {'svc_dict': {'svc': {'service': {'type': 'L2V', 'class': 'TST', 'descr': 'Ansible', 'svc_id': 500013}, 'attach_circuit_wan': [{'hostname': 'PE01LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'dot1q', 'mtu': '9212', 'vlan': '12', 'sap_descr': 'Automation', 'qos': 'BE', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE01LT2', 'port': '1/2/11', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'qinq', 'mtu': '9212', 'vlan': '100.*', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE02LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'null', 'mtu': '9212', 'vlan': '', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}]}}} on 2 hosts
2020-10-14 17:23:51,579 -  nornir.core -     INFO -        run() - Running task 'send_xml_payload' with args {} on 2 hosts
2020-10-14 17:25:20,816 -  nornir.core -     INFO -        run() - Running task 'port_cfg_xml_generation' with args {'svc_dict': {'svc': {'service': {'type': 'L2V', 'class': 'TST', 'descr': 'Ansible', 'svc_id': 500013}, 'attach_circuit_wan': [{'hostname': 'PE01LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'dot1q', 'mtu': '9212', 'vlan': '12', 'sap_descr': 'Automation', 'qos': 'BE', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE01LT2', 'port': '1/2/11', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'qinq', 'mtu': '9212', 'vlan': '100.*', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE02LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'null', 'mtu': '9212', 'vlan': '', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}]}}, 'attr_dict': {'pe': {'loopback': {'PE01LT2': {'id': 1}, 'PE02LT2': {'id': 2}}, 'qos': {'BE': {'fprdgrp': 'dc-vxlan-be', 'qos_id': 1, 'queue_id': 1}, 'AF': {'fprdgrp': 'dc-vxlan-af', 'qos_id': 6003, 'queue_id': 3}, 'EF': {'fprdgrp': 'dc-vxlan-ef', 'qos_id': 6001, 'queue_id': 6}, 'H1': {'fprdgrp': 'dc-vxlan-h1', 'qos_id': 6000, 'queue_id': 7}}}}} on 2 hosts
2020-10-14 17:25:20,826 -  nornir.core -     INFO -        run() - Running task 'full_cfg_xml_generation' with args {'svc_dict': {'svc': {'service': {'type': 'L2V', 'class': 'TST', 'descr': 'Ansible', 'svc_id': 500013}, 'attach_circuit_wan': [{'hostname': 'PE01LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'dot1q', 'mtu': '9212', 'vlan': '12', 'sap_descr': 'Automation', 'qos': 'BE', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE01LT2', 'port': '1/2/11', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'qinq', 'mtu': '9212', 'vlan': '100.*', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE02LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'null', 'mtu': '9212', 'vlan': '', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}]}}} on 2 hosts
2020-10-14 17:25:20,838 -  nornir.core -     INFO -        run() - Running task 'send_xml_payload' with args {} on 2 hosts
2020-10-14 17:25:46,078 -  nornir.core -     INFO -        run() - Running task 'svc_cfg_xml_generation' with args {'svc_dict': {'svc': {'service': {'type': 'L2V', 'class': 'TST', 'descr': 'Ansible', 'svc_id': 500013}, 'attach_circuit_wan': [{'hostname': 'PE01LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'dot1q', 'mtu': '9212', 'vlan': '12', 'sap_descr': 'Automation', 'qos': 'BE', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE01LT2', 'port': '1/2/11', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'qinq', 'mtu': '9212', 'vlan': '100.*', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE02LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'null', 'mtu': '9212', 'vlan': '', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}]}}, 'attr_dict': {'pe': {'loopback': {'PE01LT2': {'id': 1}, 'PE02LT2': {'id': 2}}, 'qos': {'BE': {'fprdgrp': 'dc-vxlan-be', 'qos_id': 1, 'queue_id': 1}, 'AF': {'fprdgrp': 'dc-vxlan-af', 'qos_id': 6003, 'queue_id': 3}, 'EF': {'fprdgrp': 'dc-vxlan-ef', 'qos_id': 6001, 'queue_id': 6}, 'H1': {'fprdgrp': 'dc-vxlan-h1', 'qos_id': 6000, 'queue_id': 7}}}}} on 2 hosts
2020-10-14 17:25:46,089 -  nornir.core -     INFO -        run() - Running task 'full_cfg_xml_generation' with args {'svc_dict': {'svc': {'service': {'type': 'L2V', 'class': 'TST', 'descr': 'Ansible', 'svc_id': 500013}, 'attach_circuit_wan': [{'hostname': 'PE01LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'dot1q', 'mtu': '9212', 'vlan': '12', 'sap_descr': 'Automation', 'qos': 'BE', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE01LT2', 'port': '1/2/11', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'qinq', 'mtu': '9212', 'vlan': '100.*', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE02LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'null', 'mtu': '9212', 'vlan': '', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}]}}} on 2 hosts
2020-10-14 17:25:46,100 -  nornir.core -     INFO -        run() - Running task 'send_xml_payload' with args {} on 2 hosts
2020-10-14 17:26:12,684 -  nornir.core -     INFO -        run() - Running task 'sap_cfg_xml_generation' with args {'svc_dict': {'svc': {'service': {'type': 'L2V', 'class': 'TST', 'descr': 'Ansible', 'svc_id': 500013}, 'attach_circuit_wan': [{'hostname': 'PE01LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'dot1q', 'mtu': '9212', 'vlan': '12', 'sap_descr': 'Automation', 'qos': 'BE', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE01LT2', 'port': '1/2/11', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'qinq', 'mtu': '9212', 'vlan': '100.*', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE02LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'null', 'mtu': '9212', 'vlan': '', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}]}}, 'attr_dict': {'pe': {'loopback': {'PE01LT2': {'id': 1}, 'PE02LT2': {'id': 2}}, 'qos': {'BE': {'fprdgrp': 'dc-vxlan-be', 'qos_id': 1, 'queue_id': 1}, 'AF': {'fprdgrp': 'dc-vxlan-af', 'qos_id': 6003, 'queue_id': 3}, 'EF': {'fprdgrp': 'dc-vxlan-ef', 'qos_id': 6001, 'queue_id': 6}, 'H1': {'fprdgrp': 'dc-vxlan-h1', 'qos_id': 6000, 'queue_id': 7}}}}} on 2 hosts
2020-10-14 17:26:12,700 -  nornir.core -     INFO -        run() - Running task 'full_cfg_xml_generation' with args {'svc_dict': {'svc': {'service': {'type': 'L2V', 'class': 'TST', 'descr': 'Ansible', 'svc_id': 500013}, 'attach_circuit_wan': [{'hostname': 'PE01LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'dot1q', 'mtu': '9212', 'vlan': '12', 'sap_descr': 'Automation', 'qos': 'BE', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE01LT2', 'port': '1/2/11', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'qinq', 'mtu': '9212', 'vlan': '100.*', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE02LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'null', 'mtu': '9212', 'vlan': '', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}]}}} on 2 hosts
2020-10-14 17:26:12,713 -  nornir.core -     INFO -        run() - Running task 'send_xml_payload' with args {} on 2 hosts
2020-10-14 17:27:21,998 -  nornir.core -     INFO -        run() - Running task 'sap_cfg_xml_generation' with args {'svc_dict': {'svc': {'service': {'type': 'L2V', 'class': 'TST', 'descr': 'Ansible', 'svc_id': 500013}, 'attach_circuit_wan': [{'hostname': 'PE01LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'dot1q', 'mtu': '9212', 'vlan': '12', 'sap_descr': 'Automation', 'qos': 'BE', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE01LT2', 'port': '1/2/11', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'qinq', 'mtu': '9212', 'vlan': '100.*', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE02LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'null', 'mtu': '9212', 'vlan': '', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}]}}, 'attr_dict': {'pe': {'loopback': {'PE01LT2': {'id': 1}, 'PE02LT2': {'id': 2}}, 'qos': {'BE': {'fprdgrp': 'dc-vxlan-be', 'qos_id': 1, 'queue_id': 1}, 'AF': {'fprdgrp': 'dc-vxlan-af', 'qos_id': 6003, 'queue_id': 3}, 'EF': {'fprdgrp': 'dc-vxlan-ef', 'qos_id': 6001, 'queue_id': 6}, 'H1': {'fprdgrp': 'dc-vxlan-h1', 'qos_id': 6000, 'queue_id': 7}}}}} on 2 hosts
2020-10-14 17:27:22,016 -  nornir.core -     INFO -        run() - Running task 'full_cfg_xml_generation' with args {'svc_dict': {'svc': {'service': {'type': 'L2V', 'class': 'TST', 'descr': 'Ansible', 'svc_id': 500013}, 'attach_circuit_wan': [{'hostname': 'PE01LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'dot1q', 'mtu': '9212', 'vlan': '12', 'sap_descr': 'Automation', 'qos': 'BE', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE01LT2', 'port': '1/2/11', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'qinq', 'mtu': '9212', 'vlan': '100.*', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE02LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'null', 'mtu': '9212', 'vlan': '', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}]}}} on 2 hosts
2020-10-14 17:27:22,029 -  nornir.core -     INFO -        run() - Running task 'send_xml_payload' with args {} on 2 hosts
2020-10-14 17:29:43,488 -  nornir.core -     INFO -        run() - Running task 'svc_cfg_xml_generation' with args {'svc_dict': {'svc': {'service': {'type': 'L2V', 'class': 'TST', 'descr': 'Ansible', 'svc_id': 500013}, 'attach_circuit_wan': [{'hostname': 'PE01LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'dot1q', 'mtu': '9212', 'vlan': '12', 'sap_descr': 'Automation', 'qos': 'BE', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE01LT2', 'port': '1/2/11', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'qinq', 'mtu': '9212', 'vlan': '100.*', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE02LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'null', 'mtu': '9212', 'vlan': '', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}]}}, 'attr_dict': {'pe': {'loopback': {'PE01LT2': {'id': 1}, 'PE02LT2': {'id': 2}}, 'qos': {'BE': {'fprdgrp': 'dc-vxlan-be', 'qos_id': 1, 'queue_id': 1}, 'AF': {'fprdgrp': 'dc-vxlan-af', 'qos_id': 6003, 'queue_id': 3}, 'EF': {'fprdgrp': 'dc-vxlan-ef', 'qos_id': 6001, 'queue_id': 6}, 'H1': {'fprdgrp': 'dc-vxlan-h1', 'qos_id': 6000, 'queue_id': 7}}}}} on 2 hosts
2020-10-14 17:29:43,501 -  nornir.core -     INFO -        run() - Running task 'full_cfg_xml_generation' with args {'svc_dict': {'svc': {'service': {'type': 'L2V', 'class': 'TST', 'descr': 'Ansible', 'svc_id': 500013}, 'attach_circuit_wan': [{'hostname': 'PE01LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'dot1q', 'mtu': '9212', 'vlan': '12', 'sap_descr': 'Automation', 'qos': 'BE', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE01LT2', 'port': '1/2/11', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'qinq', 'mtu': '9212', 'vlan': '100.*', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE02LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'null', 'mtu': '9212', 'vlan': '', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}]}}} on 2 hosts
2020-10-14 17:29:43,513 -  nornir.core -     INFO -        run() - Running task 'send_xml_payload' with args {} on 2 hosts
2020-10-14 17:32:07,826 -  nornir.core -     INFO -        run() - Running task 'sap_cfg_xml_generation' with args {'svc_dict': {'svc': {'service': {'type': 'L2V', 'class': 'TST', 'descr': 'Ansible', 'svc_id': 500013}, 'attach_circuit_wan': [{'hostname': 'PE01LT2', 'port': '1/2/11', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'qinq', 'mtu': '9212', 'vlan': '100.*', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE02LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'null', 'mtu': '9212', 'vlan': '', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}]}}, 'attr_dict': {'pe': {'loopback': {'PE01LT2': {'id': 1}, 'PE02LT2': {'id': 2}}, 'qos': {'BE': {'fprdgrp': 'dc-vxlan-be', 'qos_id': 1, 'queue_id': 1}, 'AF': {'fprdgrp': 'dc-vxlan-af', 'qos_id': 6003, 'queue_id': 3}, 'EF': {'fprdgrp': 'dc-vxlan-ef', 'qos_id': 6001, 'queue_id': 6}, 'H1': {'fprdgrp': 'dc-vxlan-h1', 'qos_id': 6000, 'queue_id': 7}}}}} on 2 hosts
2020-10-14 17:32:07,842 -  nornir.core -     INFO -        run() - Running task 'full_cfg_xml_generation' with args {'svc_dict': {'svc': {'service': {'type': 'L2V', 'class': 'TST', 'descr': 'Ansible', 'svc_id': 500013}, 'attach_circuit_wan': [{'hostname': 'PE01LT2', 'port': '1/2/11', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'qinq', 'mtu': '9212', 'vlan': '100.*', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}, {'hostname': 'PE02LT2', 'port': '1/2/10', 'port_nd': '60961313', 'port_descr': 'Automation', 'port_encap': 'null', 'mtu': '9212', 'vlan': '', 'sap_descr': 'Automation', 'qos': 'AF', 'cir': '1000', 'pir': '1000'}]}}} on 2 hosts
2020-10-14 17:32:07,855 -  nornir.core -     INFO -        run() - Running task 'send_xml_payload' with args {} on 2 hosts
